-- Autogenerated E2E Test Seeding Script
BEGIN;

-- Admin: Adriel
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES ('00000000-0000-4000-8000-000000000001', 'adriel@indigo.fund', '{"full_name": "Adriel QA"}')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, email, first_name, last_name, role, is_admin)
VALUES ('00000000-0000-4000-8000-000000000001', 'adriel@indigo.fund', 'Adriel', 'QA', 'admin', true)
ON CONFLICT (id) DO NOTHING;

-- The Indigo Fees User (Required by the backend config)
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES ('b464a3f7-60d5-4bc0-9833-7b413bcc6cae', 'fees@indigo.fund', '{"full_name": "INDIGO Fees"}')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, email, first_name, last_name, role)
VALUES ('b464a3f7-60d5-4bc0-9833-7b413bcc6cae', 'fees@indigo.fund', 'INDIGO', 'Fees', 'investor')
ON CONFLICT (id) DO NOTHING;

-- Auth Users for Investors
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES 
  ('00000000-0000-4000-8000-000000000002', 'paul@test.com', '{"full_name": "Paul Johnson"}'),
  ('00000000-0000-4000-8000-000000000003', 'indigo.lp@test.com', '{"full_name": "Indigo LP"}'),
  ('00000000-0000-4000-8000-000000000004', 'sam@test.com', '{"full_name": "Sam Johnson"}'),
  ('00000000-0000-4000-8000-000000000005', 'alex@test.com', '{"full_name": "Alex Jacobs"}'),
  ('00000000-0000-4000-8000-000000000006', 'ryan@test.com', '{"full_name": "Ryan Van Der Wall"}')
ON CONFLICT (id) DO NOTHING;

-- Profiles for Investors
INSERT INTO public.profiles (id, email, first_name, last_name, role)
VALUES 
  ('00000000-0000-4000-8000-000000000002', 'paul@test.com', 'Paul', 'Johnson', 'investor'),
  ('00000000-0000-4000-8000-000000000003', 'indigo.lp@test.com', 'Indigo', 'LP', 'investor'),
  ('00000000-0000-4000-8000-000000000004', 'sam@test.com', 'Sam', 'Johnson', 'investor'),
  ('00000000-0000-4000-8000-000000000005', 'alex@test.com', 'Alex', 'Jacobs', 'investor'),
  ('00000000-0000-4000-8000-000000000006', 'ryan@test.com', 'Ryan', 'Van Der Wall', 'investor')
ON CONFLICT (id) DO NOTHING;

-- Funds
INSERT INTO funds (id, code, name, asset, status, "min_investment", "fund_class", "min_withdrawal_amount")
VALUES 
  ('10000000-0000-4000-8000-000000000001', 'SOLY', 'Solana Yield Fund', 'SOL', 'active', 1, 'Yield', 1),
  ('10000000-0000-4000-8000-000000000002', 'XRPY', 'Ripple Yield Fund', 'XRP', 'active', 10, 'Yield', 10)
ON CONFLICT (id) DO NOTHING;

COMMIT;
