/**
 * Database Schema Contracts
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Provides table metadata for runtime validation and IDE support.
 * Regenerate with: npm run contracts:generate
 */

import type { Database } from "@/integrations/supabase/types";

// =============================================================================
// TABLE METADATA
// =============================================================================

export const DB_TABLES = {
  access_logs: {
    name: "access_logs" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "device_label",
      "event",
      "id",
      "ip",
      "success",
      "user_agent",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  accounting_periods: {
    name: "accounting_periods" as const,
    primaryKey: ["id"] as const,
    columns: [
      "approved_at",
      "approved_by",
      "created_at",
      "fund_id",
      "id",
      "locked_at",
      "locked_by",
      "notes",
      "period_end",
      "period_start",
      "reviewed_at",
      "reviewed_by",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  admin_alerts: {
    name: "admin_alerts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "acknowledged_at",
      "acknowledged_by",
      "alert_type",
      "created_at",
      "id",
      "message",
      "metadata",
      "notification_channel",
      "notification_sent_at",
      "related_run_id",
      "severity",
      "title",
    ] as const,
    rlsEnabled: true,
  },
  admin_approvals: {
    name: "admin_approvals" as const,
    primaryKey: ["id"] as const,
    columns: [
      "action_type",
      "actual_value",
      "approval_signature",
      "approval_status",
      "approved_by",
      "entity_id",
      "entity_type",
      "expires_at",
      "id",
      "metadata",
      "operation_type",
      "reason",
      "rejection_reason",
      "requested_at",
      "requested_by",
      "resolved_at",
      "threshold_value",
    ] as const,
    rlsEnabled: true,
  },
  admin_integrity_runs: {
    name: "admin_integrity_runs" as const,
    primaryKey: ["id"] as const,
    columns: [
      "context",
      "created_by",
      "id",
      "run_at",
      "runtime_ms",
      "scope_fund_id",
      "scope_investor_id",
      "status",
      "triggered_by",
      "violations",
    ] as const,
    rlsEnabled: true,
  },
  admin_invites: {
    name: "admin_invites" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "email",
      "expires_at",
      "id",
      "intended_role",
      "invite_code",
      "used",
    ] as const,
    rlsEnabled: true,
  },
  assets: {
    name: "assets" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "decimal_places",
      "icon_url",
      "id",
      "is_active",
      "name",
      "symbol",
    ] as const,
    rlsEnabled: true,
  },
  audit_log: {
    name: "audit_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "action",
      "actor_user",
      "created_at",
      "entity",
      "entity_id",
      "id",
      "meta",
      "new_values",
      "old_values",
    ] as const,
    rlsEnabled: true,
  },
  correction_runs: {
    name: "correction_runs" as const,
    primaryKey: ["id"] as const,
    columns: [
      "completed_at",
      "correction_type",
      "created_at",
      "created_by",
      "effective_date",
      "fund_id",
      "id",
      "input_hash",
      "parameters",
      "result",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  daily_nav: {
    name: "daily_nav" as const,
    primaryKey: null as const,
    columns: [
      "aum",
      "created_at",
      "created_by",
      "fees_accrued",
      "fund_id",
      "gross_return_pct",
      "high_water_mark",
      "investor_count",
      "is_month_end",
      "nav_date",
      "nav_per_share",
      "net_return_pct",
      "purpose",
      "shares_outstanding",
      "total_inflows",
      "total_outflows",
    ] as const,
    rlsEnabled: true,
  },
  daily_rates: {
    name: "daily_rates" as const,
    primaryKey: ["id"] as const,
    columns: [
      "btc_rate",
      "created_at",
      "created_by",
      "eth_rate",
      "eurc_rate",
      "id",
      "notes",
      "rate_date",
      "sol_rate",
      "updated_at",
      "usdc_rate",
      "usdt_rate",
      "xaut_rate",
      "xrp_rate",
    ] as const,
    rlsEnabled: true,
  },
  data_edit_audit: {
    name: "data_edit_audit" as const,
    primaryKey: ["id"] as const,
    columns: [
      "changed_fields",
      "edit_source",
      "edited_at",
      "edited_by",
      "id",
      "import_id",
      "import_related",
      "new_data",
      "old_data",
      "operation",
      "record_id",
      "table_name",
      "voided_record",
    ] as const,
    rlsEnabled: true,
  },
  documents: {
    name: "documents" as const,
    primaryKey: ["id"] as const,
    columns: [
      "checksum",
      "created_at",
      "created_by",
      "created_by_profile_id",
      "fund_id",
      "id",
      "period_end",
      "period_start",
      "storage_path",
      "title",
      "type",
      "user_id",
      "user_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  error_code_metadata: {
    name: "error_code_metadata" as const,
    primaryKey: null as const,
    columns: [
      "category",
      "created_at",
      "default_message",
      "error_code",
      "is_retryable",
      "severity",
      "ui_action",
      "user_action_hint",
    ] as const,
    rlsEnabled: true,
  },
  fee_allocations: {
    name: "fee_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "base_net_income",
      "created_at",
      "created_by",
      "credit_transaction_id",
      "debit_transaction_id",
      "distribution_id",
      "fee_amount",
      "fee_percentage",
      "fees_account_id",
      "fund_id",
      "id",
      "investor_id",
      "is_voided",
      "period_end",
      "period_start",
      "purpose",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  fund_aum_events: {
    name: "fund_aum_events" as const,
    primaryKey: ["id"] as const,
    columns: [
      "closing_aum",
      "created_at",
      "created_by",
      "event_date",
      "event_ts",
      "fund_id",
      "id",
      "is_voided",
      "opening_aum",
      "post_flow_aum",
      "purpose",
      "trigger_reference",
      "trigger_type",
      "void_reason",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  fund_daily_aum: {
    name: "fund_daily_aum" as const,
    primaryKey: ["id"] as const,
    columns: [
      "as_of_date",
      "aum_date",
      "created_at",
      "created_by",
      "fund_id",
      "id",
      "is_month_end",
      "is_voided",
      "nav_per_share",
      "purpose",
      "source",
      "temporal_lock_bypass",
      "total_aum",
      "total_shares",
      "updated_at",
      "updated_by",
      "void_reason",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  fund_daily_aum_archive: {
    name: "fund_daily_aum_archive" as const,
    primaryKey: ["id"] as const,
    columns: [
      "archive_id",
      "archived_at",
      "archived_by",
      "as_of_date",
      "aum_date",
      "fund_id",
      "id",
      "nav_per_share",
      "original_created_at",
      "reset_batch_id",
      "source",
      "total_aum",
      "total_shares",
    ] as const,
    rlsEnabled: true,
  },
  fund_yield_snapshots: {
    name: "fund_yield_snapshots" as const,
    primaryKey: ["id"] as const,
    columns: [
      "closing_aum",
      "created_at",
      "created_by",
      "days_in_period",
      "fund_id",
      "gross_yield_amount",
      "gross_yield_pct",
      "id",
      "opening_aum",
      "period_end",
      "period_start",
      "snapshot_date",
      "trigger_reference",
      "trigger_type",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  funds: {
    name: "funds" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "code",
      "cooling_off_hours",
      "created_at",
      "fund_class",
      "high_water_mark",
      "id",
      "inception_date",
      "large_withdrawal_threshold",
      "lock_period_days",
      "logo_url",
      "max_daily_yield_pct",
      "mgmt_fee_bps",
      "min_investment",
      "name",
      "perf_fee_bps",
      "status",
      "strategy",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  generated_reports: {
    name: "generated_reports" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "fund_id",
      "html_content",
      "id",
      "investor_id",
      "pdf_url",
      "report_data",
      "report_month",
      "report_name",
      "report_type",
      "status",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  generated_statements: {
    name: "generated_statements" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "fund_names",
      "generated_by",
      "html_content",
      "id",
      "investor_id",
      "pdf_url",
      "period_id",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  global_fee_settings: {
    name: "global_fee_settings" as const,
    primaryKey: null as const,
    columns: ["description", "setting_key", "updated_at", "updated_by", "value"] as const,
    rlsEnabled: true,
  },
  ib_allocations: {
    name: "ib_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "distribution_id",
      "effective_date",
      "fund_id",
      "ib_fee_amount",
      "ib_investor_id",
      "ib_percentage",
      "id",
      "is_voided",
      "paid_at",
      "paid_by",
      "payout_batch_id",
      "payout_status",
      "period_end",
      "period_id",
      "period_start",
      "purpose",
      "source",
      "source_investor_id",
      "source_net_income",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  ib_commission_ledger: {
    name: "ib_commission_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fund_id",
      "gross_yield_amount",
      "ib_commission_amount",
      "ib_id",
      "ib_name",
      "ib_percentage",
      "id",
      "is_voided",
      "source_investor_id",
      "source_investor_name",
      "transaction_id",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  investor_daily_balance: {
    name: "investor_daily_balance" as const,
    primaryKey: ["id"] as const,
    columns: [
      "balance_date",
      "created_at",
      "end_of_day_balance",
      "fund_id",
      "id",
      "investor_id",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_emails: {
    name: "investor_emails" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "email",
      "id",
      "investor_id",
      "is_primary",
      "updated_at",
      "verified",
    ] as const,
    rlsEnabled: true,
  },
  investor_fee_schedule: {
    name: "investor_fee_schedule" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "effective_date",
      "end_date",
      "fee_pct",
      "fund_id",
      "id",
      "investor_id",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_fund_performance: {
    name: "investor_fund_performance" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "fund_name",
      "id",
      "investor_id",
      "itd_additions",
      "itd_beginning_balance",
      "itd_ending_balance",
      "itd_net_income",
      "itd_rate_of_return",
      "itd_redemptions",
      "mtd_additions",
      "mtd_beginning_balance",
      "mtd_ending_balance",
      "mtd_net_income",
      "mtd_rate_of_return",
      "mtd_redemptions",
      "period_id",
      "purpose",
      "qtd_additions",
      "qtd_beginning_balance",
      "qtd_ending_balance",
      "qtd_net_income",
      "qtd_rate_of_return",
      "qtd_redemptions",
      "updated_at",
      "ytd_additions",
      "ytd_beginning_balance",
      "ytd_ending_balance",
      "ytd_net_income",
      "ytd_rate_of_return",
      "ytd_redemptions",
    ] as const,
    rlsEnabled: true,
  },
  investor_fund_performance_archive: {
    name: "investor_fund_performance_archive" as const,
    primaryKey: ["id"] as const,
    columns: [
      "archive_id",
      "archived_at",
      "archived_by",
      "fund_name",
      "id",
      "investor_id",
      "itd_additions",
      "itd_beginning_balance",
      "itd_ending_balance",
      "itd_net_income",
      "itd_rate_of_return",
      "itd_redemptions",
      "mtd_additions",
      "mtd_beginning_balance",
      "mtd_ending_balance",
      "mtd_net_income",
      "mtd_rate_of_return",
      "mtd_redemptions",
      "original_created_at",
      "original_updated_at",
      "period_id",
      "qtd_additions",
      "qtd_beginning_balance",
      "qtd_ending_balance",
      "qtd_net_income",
      "qtd_rate_of_return",
      "qtd_redemptions",
      "reset_batch_id",
      "ytd_additions",
      "ytd_beginning_balance",
      "ytd_ending_balance",
      "ytd_net_income",
      "ytd_rate_of_return",
      "ytd_redemptions",
    ] as const,
    rlsEnabled: true,
  },
  investor_invites: {
    name: "investor_invites" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "email",
      "expires_at",
      "id",
      "investor_id",
      "invite_code",
      "used",
      "used_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_loss_carryforward: {
    name: "investor_loss_carryforward" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "fund_id",
      "id",
      "investor_id",
      "loss_amount",
      "offset_by_distribution_id",
      "original_distribution_id",
      "period_end",
      "remaining_loss",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_position_snapshots: {
    name: "investor_position_snapshots" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "current_value",
      "fund_id",
      "id",
      "investor_id",
      "snapshot_date",
      "snapshot_source",
    ] as const,
    rlsEnabled: true,
  },
  investor_positions: {
    name: "investor_positions" as const,
    primaryKey: null as const,
    columns: [
      "aum_percentage",
      "cost_basis",
      "cumulative_yield_earned",
      "current_value",
      "fund_class",
      "fund_id",
      "high_water_mark",
      "investor_id",
      "is_active",
      "last_transaction_date",
      "last_yield_crystallization_date",
      "lock_until_date",
      "mgmt_fees_paid",
      "perf_fees_paid",
      "realized_pnl",
      "shares",
      "unrealized_pnl",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_positions_archive: {
    name: "investor_positions_archive" as const,
    primaryKey: null as const,
    columns: [
      "archive_id",
      "archived_at",
      "archived_by",
      "aum_percentage",
      "cost_basis",
      "current_value",
      "fund_class",
      "fund_id",
      "high_water_mark",
      "investor_id",
      "last_transaction_date",
      "lock_until_date",
      "mgmt_fees_paid",
      "original_updated_at",
      "perf_fees_paid",
      "realized_pnl",
      "reset_batch_id",
      "shares",
      "unrealized_pnl",
    ] as const,
    rlsEnabled: true,
  },
  investor_yield_events: {
    name: "investor_yield_events" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "days_in_period",
      "event_date",
      "fee_amount",
      "fee_pct",
      "fund_aum_after",
      "fund_aum_before",
      "fund_id",
      "fund_yield_pct",
      "gross_yield_amount",
      "id",
      "investor_balance",
      "investor_id",
      "investor_share_pct",
      "is_voided",
      "made_visible_at",
      "made_visible_by",
      "net_yield_amount",
      "period_end",
      "period_start",
      "reference_id",
      "trigger_transaction_id",
      "trigger_type",
      "visibility_scope",
      "voided_at",
      "voided_by",
    ] as const,
    rlsEnabled: true,
  },
  mfa_reset_requests: {
    name: "mfa_reset_requests" as const,
    primaryKey: ["id"] as const,
    columns: [
      "approval_signature",
      "approved_at",
      "approved_by",
      "created_at",
      "executed_at",
      "expires_at",
      "id",
      "rejected_at",
      "rejected_by",
      "rejection_reason",
      "request_reason",
      "requested_at",
      "requester_ip",
      "requester_user_agent",
      "status",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  notification_settings: {
    name: "notification_settings" as const,
    primaryKey: null as const,
    columns: [
      "daily_rates_enabled",
      "email_enabled",
      "notification_types",
      "push_enabled",
      "sms_enabled",
      "updated_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  notifications: {
    name: "notifications" as const,
    primaryKey: ["id"] as const,
    columns: [
      "body",
      "created_at",
      "data_jsonb",
      "id",
      "priority",
      "read_at",
      "title",
      "type",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  operation_approvals: {
    name: "operation_approvals" as const,
    primaryKey: ["id"] as const,
    columns: [
      "actual_value",
      "created_at",
      "created_by",
      "expires_at",
      "first_approval_notes",
      "first_approved_at",
      "first_approver_id",
      "id",
      "operation_details",
      "operation_id",
      "operation_type",
      "second_approval_notes",
      "second_approved_at",
      "second_approver_id",
      "status",
      "threshold_exceeded",
      "threshold_value",
    ] as const,
    rlsEnabled: true,
  },
  operation_metrics: {
    name: "operation_metrics" as const,
    primaryKey: ["id"] as const,
    columns: [
      "completed_at",
      "created_at",
      "duration_ms",
      "error_code",
      "error_message",
      "fund_id",
      "id",
      "input_params",
      "operation_id",
      "operation_name",
      "output_result",
      "started_at",
      "success",
    ] as const,
    rlsEnabled: true,
  },
  platform_fee_ledger: {
    name: "platform_fee_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fee_amount",
      "fee_percentage",
      "fund_id",
      "gross_yield_amount",
      "id",
      "investor_id",
      "investor_name",
      "is_voided",
      "transaction_id",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  position_correction_log: {
    name: "position_correction_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "corrected_at",
      "corrected_by",
      "fund_id",
      "id",
      "investor_id",
      "new_value",
      "notes",
      "old_value",
      "reconciliation_batch_id",
      "variance",
      "variance_percentage",
    ] as const,
    rlsEnabled: true,
  },
  position_reconciliation_log: {
    name: "position_reconciliation_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "action_taken",
      "created_at",
      "discrepancy",
      "fund_id",
      "id",
      "investor_id",
      "ledger_value",
      "position_value",
      "reconciled_by",
    ] as const,
    rlsEnabled: true,
  },
  position_reset_log: {
    name: "position_reset_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "admin_user_id",
      "affected_counts",
      "completed_at",
      "confirmation_code",
      "error_message",
      "id",
      "initiated_at",
      "reset_batch_id",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  price_alerts: {
    name: "price_alerts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "alert_type",
      "asset_code",
      "created_at",
      "id",
      "is_active",
      "threshold_value",
      "triggered_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  profiles: {
    name: "profiles" as const,
    primaryKey: ["id"] as const,
    columns: [
      "account_type",
      "avatar_url",
      "created_at",
      "email",
      "entity_type",
      "fee_pct",
      "first_name",
      "ib_commission_source",
      "ib_parent_id",
      "ib_percentage",
      "id",
      "include_in_reporting",
      "is_admin",
      "is_system_account",
      "kyc_status",
      "last_activity_at",
      "last_name",
      "onboarding_date",
      "phone",
      "preferences",
      "status",
      "totp_enabled",
      "totp_verified",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  rate_limit_config: {
    name: "rate_limit_config" as const,
    primaryKey: null as const,
    columns: [
      "action_type",
      "created_at",
      "description",
      "is_enabled",
      "max_actions",
      "updated_at",
      "window_minutes",
    ] as const,
    rlsEnabled: true,
  },
  rate_limits: {
    name: "rate_limits" as const,
    primaryKey: ["id"] as const,
    columns: ["action_type", "actor_id", "created_at", "id", "metadata"] as const,
    rlsEnabled: true,
  },
  reconciliation_packs: {
    name: "reconciliation_packs" as const,
    primaryKey: ["id"] as const,
    columns: [
      "closing_aum",
      "distribution_count",
      "finalized_at",
      "finalized_by",
      "fund_id",
      "generated_at",
      "generated_by",
      "gross_yield",
      "id",
      "investor_count",
      "net_flows",
      "net_yield",
      "opening_aum",
      "pack_data",
      "pack_type",
      "period_end",
      "period_start",
      "status",
      "total_deposits",
      "total_dust",
      "total_fees",
      "total_withdrawals",
      "transaction_count",
      "void_count",
    ] as const,
    rlsEnabled: true,
  },
  report_change_log: {
    name: "report_change_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "change_reason",
      "change_summary",
      "changed_at",
      "changed_by",
      "created_at",
      "id",
      "previous_html_hash",
      "previous_pdf_url",
      "report_id",
      "report_table",
    ] as const,
    rlsEnabled: true,
  },
  report_delivery_events: {
    name: "report_delivery_events" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "delivery_id",
      "event_data",
      "event_type",
      "id",
      "occurred_at",
      "provider_message_id",
    ] as const,
    rlsEnabled: true,
  },
  risk_alerts: {
    name: "risk_alerts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "acknowledged",
      "acknowledged_at",
      "acknowledged_by",
      "actual_value",
      "alert_type",
      "created_at",
      "details",
      "expires_at",
      "fund_id",
      "id",
      "investor_id",
      "message",
      "resolution_notes",
      "resolved",
      "resolved_at",
      "resolved_by",
      "severity",
      "threshold_value",
    ] as const,
    rlsEnabled: true,
  },
  statement_email_delivery: {
    name: "statement_email_delivery" as const,
    primaryKey: ["id"] as const,
    columns: [
      "attempt_count",
      "bounce_type",
      "bounced_at",
      "channel",
      "clicked_at",
      "created_at",
      "created_by",
      "delivered_at",
      "delivery_mode",
      "error_code",
      "error_message",
      "failed_at",
      "id",
      "investor_id",
      "last_attempt_at",
      "locked_at",
      "locked_by",
      "metadata",
      "opened_at",
      "period_id",
      "provider",
      "provider_message_id",
      "recipient_email",
      "retry_count",
      "sent_at",
      "statement_id",
      "status",
      "subject",
      "updated_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  statement_periods: {
    name: "statement_periods" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "finalized_at",
      "finalized_by",
      "id",
      "month",
      "notes",
      "period_end_date",
      "period_name",
      "status",
      "updated_at",
      "year",
    ] as const,
    rlsEnabled: true,
  },
  statements: {
    name: "statements" as const,
    primaryKey: ["id"] as const,
    columns: [
      "additions",
      "asset_code",
      "begin_balance",
      "created_at",
      "end_balance",
      "id",
      "investor_id",
      "investor_profile_id",
      "net_income",
      "period_month",
      "period_year",
      "rate_of_return_itd",
      "rate_of_return_mtd",
      "rate_of_return_qtd",
      "rate_of_return_ytd",
      "redemptions",
      "storage_path",
    ] as const,
    rlsEnabled: true,
  },
  support_tickets: {
    name: "support_tickets" as const,
    primaryKey: ["id"] as const,
    columns: [
      "assigned_admin_id",
      "attachments",
      "category",
      "created_at",
      "id",
      "messages_jsonb",
      "priority",
      "status",
      "subject",
      "updated_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  system_2fa_policy: {
    name: "system_2fa_policy" as const,
    primaryKey: ["id"] as const,
    columns: [
      "backup_code_length",
      "backup_codes_count",
      "grace_period_days",
      "id",
      "lockout_duration_minutes",
      "max_failed_attempts",
      "require_2fa_for_admins",
      "require_2fa_for_investors",
      "updated_at",
      "updated_by",
    ] as const,
    rlsEnabled: true,
  },
  system_config: {
    name: "system_config" as const,
    primaryKey: null as const,
    columns: ["description", "key", "updated_at", "updated_by", "value"] as const,
    rlsEnabled: true,
  },
  transaction_bypass_attempts: {
    name: "transaction_bypass_attempts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "attempted_amount",
      "attempted_at",
      "attempted_source",
      "attempted_type",
      "client_info",
      "error_message",
      "fund_id",
      "id",
      "investor_id",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  transaction_import_staging: {
    name: "transaction_import_staging" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "asset",
      "batch_id",
      "created_at",
      "fund_id",
      "id",
      "imported_by",
      "investor_id",
      "notes",
      "promoted_at",
      "promoted_tx_id",
      "reference_id",
      "tx_date",
      "type",
      "validated_at",
      "validation_errors",
      "validation_status",
    ] as const,
    rlsEnabled: true,
  },
  transactions_v2: {
    name: "transactions_v2" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "approved_at",
      "approved_by",
      "asset",
      "balance_after",
      "balance_before",
      "correction_id",
      "created_at",
      "created_by",
      "distribution_id",
      "fund_class",
      "fund_id",
      "id",
      "investor_id",
      "is_system_generated",
      "is_voided",
      "meta",
      "notes",
      "purpose",
      "reference_id",
      "source",
      "transfer_id",
      "tx_date",
      "tx_hash",
      "tx_subtype",
      "type",
      "value_date",
      "visibility_scope",
      "void_reason",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  transactions_v2_archive: {
    name: "transactions_v2_archive" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "archive_id",
      "archived_at",
      "archived_by",
      "asset",
      "created_by",
      "fund_id",
      "id",
      "investor_id",
      "notes",
      "original_created_at",
      "reference_id",
      "reset_batch_id",
      "tx_date",
      "type",
    ] as const,
    rlsEnabled: true,
  },
  user_roles: {
    name: "user_roles" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "id", "role", "user_id"] as const,
    rlsEnabled: true,
  },
  user_sessions: {
    name: "user_sessions" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "device_label",
      "id",
      "ip",
      "last_seen_at",
      "refresh_token_id",
      "revoked_at",
      "revoked_by",
      "user_agent",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  user_totp_backup_codes: {
    name: "user_totp_backup_codes" as const,
    primaryKey: ["id"] as const,
    columns: [
      "code_hash",
      "created_at",
      "generated_batch_id",
      "id",
      "totp_settings_id",
      "used_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  user_totp_settings: {
    name: "user_totp_settings" as const,
    primaryKey: ["id"] as const,
    columns: [
      "algorithm",
      "backup_codes_generated_at",
      "created_at",
      "created_by",
      "digits",
      "enabled",
      "enforce_required",
      "failed_attempts",
      "id",
      "last_used_at",
      "locked_until",
      "period",
      "qr_code_shown_at",
      "recovery_used_count",
      "secret_encrypted",
      "setup_completed_at",
      "updated_at",
      "user_id",
      "verified_at",
    ] as const,
    rlsEnabled: true,
  },
  withdrawal_audit_logs: {
    name: "withdrawal_audit_logs" as const,
    primaryKey: ["id"] as const,
    columns: ["action", "actor_id", "created_at", "details", "id", "request_id"] as const,
    rlsEnabled: true,
  },
  withdrawal_requests: {
    name: "withdrawal_requests" as const,
    primaryKey: ["id"] as const,
    columns: [
      "admin_notes",
      "approved_amount",
      "approved_at",
      "approved_by",
      "approved_shares",
      "cancellation_reason",
      "cancelled_at",
      "cancelled_by",
      "created_by",
      "earliest_processing_at",
      "fund_class",
      "fund_id",
      "id",
      "investor_id",
      "notes",
      "processed_amount",
      "processed_at",
      "rejected_at",
      "rejected_by",
      "rejection_reason",
      "request_date",
      "requested_amount",
      "requested_shares",
      "settlement_date",
      "status",
      "tx_hash",
      "updated_at",
      "version",
      "withdrawal_type",
    ] as const,
    rlsEnabled: true,
  },
  yield_allocations: {
    name: "yield_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "adb_share",
      "created_at",
      "distribution_id",
      "fee_amount",
      "fee_pct",
      "fee_transaction_id",
      "fund_id",
      "gross_amount",
      "ib_amount",
      "ib_pct",
      "ib_transaction_id",
      "id",
      "investor_id",
      "is_voided",
      "net_amount",
      "ownership_pct",
      "position_value_at_calc",
      "transaction_id",
    ] as const,
    rlsEnabled: true,
  },
  yield_corrections: {
    name: "yield_corrections" as const,
    primaryKey: ["id"] as const,
    columns: [
      "applied_at",
      "applied_by",
      "correction_distribution_id",
      "created_at",
      "created_by",
      "delta_aum",
      "delta_gross_yield",
      "id",
      "investors_affected",
      "new_aum",
      "new_gross_yield",
      "old_aum",
      "old_gross_yield",
      "original_distribution_id",
      "preview_json",
      "reason",
      "rolled_back_at",
      "rolled_back_by",
      "status",
      "total_fee_delta",
      "total_ib_delta",
    ] as const,
    rlsEnabled: true,
  },
  yield_distributions: {
    name: "yield_distributions" as const,
    primaryKey: ["id"] as const,
    columns: [
      "allocation_count",
      "aum_record_id",
      "calculation_method",
      "closing_aum",
      "created_at",
      "created_by",
      "distribution_type",
      "dust_amount",
      "dust_receiver_id",
      "effective_date",
      "fund_id",
      "gross_yield",
      "gross_yield_amount",
      "id",
      "investor_count",
      "is_month_end",
      "is_voided",
      "net_yield",
      "opening_aum",
      "parent_distribution_id",
      "period_end",
      "period_start",
      "previous_aum",
      "purpose",
      "reason",
      "recorded_aum",
      "reference_id",
      "status",
      "summary_json",
      "total_fee_amount",
      "total_fees",
      "total_ib",
      "total_ib_amount",
      "total_net_amount",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_date",
      "yield_percentage",
    ] as const,
    rlsEnabled: true,
  },
  yield_edit_audit: {
    name: "yield_edit_audit" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "edit_reason",
      "edited_at",
      "edited_by",
      "id",
      "new_values",
      "previous_values",
      "record_id",
      "record_type",
    ] as const,
    rlsEnabled: true,
  },
  yield_rate_sanity_config: {
    name: "yield_rate_sanity_config" as const,
    primaryKey: ["id"] as const,
    columns: [
      "alert_threshold_pct",
      "created_at",
      "fund_id",
      "id",
      "max_daily_yield_pct",
      "min_daily_yield_pct",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  yield_rates: {
    name: "yield_rates" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset_id",
      "created_at",
      "daily_yield_percentage",
      "date",
      "entered_by",
      "id",
      "is_api_sourced",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  aum_position_reconciliation: {
    name: "aum_position_reconciliation" as const,
    primaryKey: null as const,
    columns: [
      "aum_date",
      "calculated_aum",
      "discrepancy",
      "fund_id",
      "fund_name",
      "has_discrepancy",
      "recorded_aum",
    ] as const,
    rlsEnabled: true,
  },
  fund_aum_mismatch: {
    name: "fund_aum_mismatch" as const,
    primaryKey: null as const,
    columns: [
      "aum_date",
      "calculated_aum",
      "discrepancy",
      "fund_code",
      "fund_id",
      "fund_name",
      "recorded_aum",
    ] as const,
    rlsEnabled: true,
  },
  ib_allocation_consistency: {
    name: "ib_allocation_consistency" as const,
    primaryKey: null as const,
    columns: [
      "allocated_ib_id",
      "allocated_ib_name",
      "allocation_id",
      "current_ib_id",
      "current_ib_name",
      "effective_date",
      "ib_changed_since_allocation",
      "ib_fee_amount",
      "ib_removed",
      "source_investor_id",
      "source_investor_name",
    ] as const,
    rlsEnabled: true,
  },
  investor_position_ledger_mismatch: {
    name: "investor_position_ledger_mismatch" as const,
    primaryKey: null as const,
    columns: [
      "discrepancy",
      "fund_code",
      "fund_id",
      "investor_id",
      "investor_name",
      "ledger_balance",
      "position_value",
    ] as const,
    rlsEnabled: true,
  },
  position_transaction_reconciliation: {
    name: "position_transaction_reconciliation" as const,
    primaryKey: null as const,
    columns: ["difference", "fund_id", "investor_id", "position_value", "transaction_sum"] as const,
    rlsEnabled: true,
  },
  profiles_display: {
    name: "profiles_display" as const,
    primaryKey: ["id"] as const,
    columns: [
      "account_type",
      "created_at",
      "first_name",
      "id",
      "is_system_account",
      "last_name",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  v_approval_history: {
    name: "v_approval_history" as const,
    primaryKey: null as const,
    columns: [
      "action_type",
      "actual_value",
      "approval_id",
      "approval_signature",
      "approval_status",
      "approved_by",
      "approver_name",
      "entity_id",
      "entity_type",
      "metadata",
      "reason",
      "rejection_reason",
      "requested_at",
      "requested_by",
      "requester_name",
      "resolved_at",
    ] as const,
    rlsEnabled: true,
  },
  v_aum_position_mismatch: {
    name: "v_aum_position_mismatch" as const,
    primaryKey: null as const,
    columns: [
      "asset",
      "fund_id",
      "fund_name",
      "has_mismatch",
      "latest_nav_aum",
      "mismatch_amount",
      "sum_positions",
    ] as const,
    rlsEnabled: true,
  },
  v_aum_snapshot_health: {
    name: "v_aum_snapshot_health" as const,
    primaryKey: null as const,
    columns: [
      "active_positions",
      "aum_created_at",
      "aum_source",
      "discrepancy",
      "fund_code",
      "fund_id",
      "fund_name",
      "latest_aum_date",
      "positions_sum",
      "recorded_aum",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  v_concentration_risk: {
    name: "v_concentration_risk" as const,
    primaryKey: null as const,
    columns: [
      "account_type",
      "concentration_level",
      "fund_aum",
      "fund_code",
      "fund_id",
      "investor_id",
      "investor_name",
      "ownership_pct",
      "position_value",
    ] as const,
    rlsEnabled: true,
  },
  v_cost_basis_anomalies: {
    name: "v_cost_basis_anomalies" as const,
    primaryKey: null as const,
    columns: [
      "cost_basis",
      "cost_basis_ratio",
      "current_value",
      "expected_cost_basis",
      "fund_id",
      "fund_name",
      "investor_id",
      "investor_name",
    ] as const,
    rlsEnabled: true,
  },
  v_cost_basis_mismatch: {
    name: "v_cost_basis_mismatch" as const,
    primaryKey: null as const,
    columns: [
      "computed_cost_basis",
      "computed_current_value",
      "computed_shares",
      "cost_basis_variance",
      "cost_basis_variance_pct",
      "current_value_variance",
      "fund_code",
      "fund_id",
      "investor_email",
      "investor_id",
      "investor_name",
      "position_cost_basis",
      "position_current_value",
      "position_shares",
    ] as const,
    rlsEnabled: true,
  },
  v_crystallization_dashboard: {
    name: "v_crystallization_dashboard" as const,
    primaryKey: null as const,
    columns: [
      "critical_stale",
      "fund_code",
      "fund_id",
      "fund_name",
      "never_crystallized",
      "newest_crystallization",
      "oldest_crystallization",
      "total_positions",
      "up_to_date",
      "warning_stale",
    ] as const,
    rlsEnabled: true,
  },
  v_crystallization_gaps: {
    name: "v_crystallization_gaps" as const,
    primaryKey: null as const,
    columns: [
      "cumulative_yield_earned",
      "current_value",
      "days_behind",
      "fund_code",
      "fund_id",
      "gap_type",
      "investor_email",
      "investor_id",
      "last_tx_type",
      "last_yield_crystallization_date",
      "max_tx_date",
    ] as const,
    rlsEnabled: true,
  },
  v_daily_platform_metrics_live: {
    name: "v_daily_platform_metrics_live" as const,
    primaryKey: null as const,
    columns: [
      "active_funds",
      "active_investors",
      "metric_date",
      "pending_withdrawal_amount",
      "pending_withdrawals",
      "refreshed_at",
      "total_ibs",
      "total_platform_aum",
      "yields_today",
    ] as const,
    rlsEnabled: true,
  },
  v_documents_compat: {
    name: "v_documents_compat" as const,
    primaryKey: ["id"] as const,
    columns: [
      "checksum",
      "created_at",
      "created_by",
      "created_by_profile_id",
      "fund_id",
      "id",
      "period_end",
      "period_start",
      "storage_path",
      "title",
      "type",
      "user_id",
      "user_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  v_fee_allocation_orphans: {
    name: "v_fee_allocation_orphans" as const,
    primaryKey: null as const,
    columns: [
      "allocation_id",
      "distribution_id",
      "fee_amount",
      "fund_id",
      "investor_id",
      "issue_type",
      "period_end",
      "period_start",
      "purpose",
    ] as const,
    rlsEnabled: true,
  },
  v_fee_calculation_orphans: {
    name: "v_fee_calculation_orphans" as const,
    primaryKey: ["id"] as const,
    columns: [
      "base_net_income",
      "created_at",
      "created_by",
      "credit_transaction_id",
      "debit_transaction_id",
      "distribution_id",
      "fee_amount",
      "fee_percentage",
      "fees_account_id",
      "fund_id",
      "id",
      "investor_id",
      "is_voided",
      "period_end",
      "period_start",
      "purpose",
      "voided_at",
      "voided_by",
    ] as const,
    rlsEnabled: true,
  },
  v_fund_aum_position_health: {
    name: "v_fund_aum_position_health" as const,
    primaryKey: null as const,
    columns: [
      "asset",
      "aum_date",
      "aum_source",
      "fund_id",
      "fund_name",
      "health_status",
      "latest_daily_aum",
      "position_sum",
      "status",
      "variance",
    ] as const,
    rlsEnabled: true,
  },
  v_fund_aum_position_status: {
    name: "v_fund_aum_position_status" as const,
    primaryKey: null as const,
    columns: [
      "active_investors",
      "actual_positions",
      "asset",
      "discrepancy",
      "discrepancy_pct",
      "fund_id",
      "fund_name",
      "recorded_aum",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  v_fund_summary_live: {
    name: "v_fund_summary_live" as const,
    primaryKey: null as const,
    columns: [
      "asset",
      "code",
      "fees_balance",
      "fund_id",
      "ib_balance",
      "investor_aum",
      "investor_count",
      "latest_aum",
      "latest_aum_date",
      "name",
      "status",
      "total_positions",
    ] as const,
    rlsEnabled: true,
  },
  v_ib_allocation_orphans: {
    name: "v_ib_allocation_orphans" as const,
    primaryKey: null as const,
    columns: [
      "allocation_id",
      "distribution_id",
      "effective_date",
      "ib_fee_amount",
      "ib_investor_id",
      "issue_type",
      "payout_status",
      "source_investor_id",
    ] as const,
    rlsEnabled: true,
  },
  v_investor_kpis: {
    name: "v_investor_kpis" as const,
    primaryKey: null as const,
    columns: [
      "email",
      "first_investment_date",
      "funds_invested",
      "investor_id",
      "kyc_status",
      "last_activity_date",
      "name",
      "status",
      "total_invested",
      "total_mgmt_fees",
      "total_perf_fees",
      "total_realized_pnl",
      "total_unrealized_pnl",
      "total_value",
    ] as const,
    rlsEnabled: true,
  },
  v_itd_returns: {
    name: "v_itd_returns" as const,
    primaryKey: null as const,
    columns: [
      "cost_basis",
      "current_value",
      "fund_id",
      "fund_name",
      "investor_id",
      "itd_return_pct",
      "realized_pnl",
      "unrealized_pnl",
    ] as const,
    rlsEnabled: true,
  },
  v_ledger_reconciliation: {
    name: "v_ledger_reconciliation" as const,
    primaryKey: null as const,
    columns: [
      "calculated_balance",
      "fund_code",
      "fund_id",
      "has_variance",
      "investor_email",
      "investor_id",
      "position_balance",
      "variance",
    ] as const,
    rlsEnabled: true,
  },
  v_liquidity_risk: {
    name: "v_liquidity_risk" as const,
    primaryKey: null as const,
    columns: [
      "active_positions",
      "fund_code",
      "fund_id",
      "fund_name",
      "pending_withdrawals",
      "risk_level",
      "total_aum",
      "withdrawal_ratio",
    ] as const,
    rlsEnabled: true,
  },
  v_live_investor_balances: {
    name: "v_live_investor_balances" as const,
    primaryKey: null as const,
    columns: [
      "fund_name",
      "investor_id",
      "last_reported_balance",
      "live_balance",
      "recent_deposits",
      "recent_withdrawals",
    ] as const,
    rlsEnabled: true,
  },
  v_missing_withdrawal_transactions: {
    name: "v_missing_withdrawal_transactions" as const,
    primaryKey: null as const,
    columns: [
      "fund_code",
      "fund_id",
      "investor_email",
      "investor_id",
      "processed_amount",
      "request_date",
      "request_id",
      "settlement_date",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  v_orphaned_positions: {
    name: "v_orphaned_positions" as const,
    primaryKey: null as const,
    columns: [
      "current_value",
      "fund_id",
      "fund_missing",
      "investor_id",
      "investor_missing",
      "last_transaction_date",
      "orphan_type",
      "shares",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  v_pending_approvals: {
    name: "v_pending_approvals" as const,
    primaryKey: null as const,
    columns: [
      "action_description",
      "action_type",
      "actual_value",
      "approval_id",
      "entity_id",
      "entity_type",
      "expires_at",
      "expiry_status",
      "metadata",
      "reason",
      "requested_at",
      "requested_by",
      "requester_email",
      "requester_name",
      "threshold_value",
    ] as const,
    rlsEnabled: true,
  },
  v_position_transaction_variance: {
    name: "v_position_transaction_variance" as const,
    primaryKey: null as const,
    columns: [
      "balance_variance",
      "cost_basis",
      "fund_code",
      "fund_id",
      "investor_email",
      "investor_id",
      "position_value",
      "total_deposits",
      "total_fees",
      "total_interest",
      "total_withdrawals",
    ] as const,
    rlsEnabled: true,
  },
  v_potential_duplicate_profiles: {
    name: "v_potential_duplicate_profiles" as const,
    primaryKey: null as const,
    columns: [
      "duplicate_type",
      "emails",
      "first_created",
      "last_created",
      "match_key",
      "names",
      "profile_count",
      "profile_ids",
      "total_funds_affected",
      "total_value_affected",
    ] as const,
    rlsEnabled: true,
  },
  v_statements_compat: {
    name: "v_statements_compat" as const,
    primaryKey: ["id"] as const,
    columns: [
      "additions",
      "asset_code",
      "begin_balance",
      "created_at",
      "end_balance",
      "id",
      "investor_id",
      "investor_profile_id",
      "net_income",
      "period_month",
      "period_year",
      "rate_of_return_itd",
      "rate_of_return_mtd",
      "rate_of_return_qtd",
      "rate_of_return_ytd",
      "redemptions",
      "storage_path",
    ] as const,
    rlsEnabled: true,
  },
  v_transaction_distribution_orphans: {
    name: "v_transaction_distribution_orphans" as const,
    primaryKey: null as const,
    columns: [
      "amount",
      "distribution_id",
      "fund_id",
      "investor_id",
      "issue_type",
      "purpose",
      "transaction_id",
      "transaction_type",
      "tx_date",
    ] as const,
    rlsEnabled: true,
  },
  v_transaction_sources: {
    name: "v_transaction_sources" as const,
    primaryKey: null as const,
    columns: ["first_tx", "last_tx", "source", "tx_count", "type"] as const,
    rlsEnabled: true,
  },
  v_yield_calculation_health: {
    name: "v_yield_calculation_health" as const,
    primaryKey: null as const,
    columns: ["details", "status", "test_name"] as const,
    rlsEnabled: true,
  },
  v_yield_conservation_violations: {
    name: "v_yield_conservation_violations" as const,
    primaryKey: null as const,
    columns: [
      "created_at",
      "distribution_id",
      "fund_code",
      "fund_id",
      "has_violation",
      "header_dust",
      "header_fee",
      "header_gross",
      "header_ib",
      "header_net",
      "header_variance",
      "is_voided",
      "period_end",
      "period_start",
      "purpose",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  withdrawal_audit_log: {
    name: "withdrawal_audit_log" as const,
    primaryKey: ["id"] as const,
    columns: ["action", "actor_id", "created_at", "details", "id", "request_id"] as const,
    rlsEnabled: true,
  },
  withdrawal_queue: {
    name: "withdrawal_queue" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "fund_id",
      "fund_name",
      "id",
      "investor_id",
      "notes",
      "processed_at",
      "requested_at",
      "status",
    ] as const,
    rlsEnabled: true,
  },
  yield_distribution_conservation_check: {
    name: "yield_distribution_conservation_check" as const,
    primaryKey: null as const,
    columns: [
      "actual_deductions",
      "calculated_fees",
      "calculated_ib",
      "conservation_error",
      "distribution_id",
      "effective_date",
      "expected_deductions",
      "fund_code",
      "fund_id",
      "gross_yield",
      "net_to_investors",
    ] as const,
    rlsEnabled: true,
  },
} as const;

export type TableName = keyof typeof DB_TABLES;

export type TableColumns<T extends TableName> = (typeof DB_TABLES)[T]["columns"][number];

export type TablePrimaryKey<T extends TableName> = (typeof DB_TABLES)[T]["primaryKey"];

// =============================================================================
// COMPOSITE PRIMARY KEY DETECTION
// =============================================================================

/** Tables with composite primary keys (no single "id" column) */
export const COMPOSITE_PK_TABLES = [
  "daily_nav",
  "error_code_metadata",
  "global_fee_settings",
  "investor_positions",
  "investor_positions_archive",
  "notification_settings",
  "rate_limit_config",
  "system_config",
  "aum_position_reconciliation",
  "fund_aum_mismatch",
  "ib_allocation_consistency",
  "investor_position_ledger_mismatch",
  "position_transaction_reconciliation",
  "v_approval_history",
  "v_aum_position_mismatch",
  "v_aum_snapshot_health",
  "v_concentration_risk",
  "v_cost_basis_anomalies",
  "v_cost_basis_mismatch",
  "v_crystallization_dashboard",
  "v_crystallization_gaps",
  "v_daily_platform_metrics_live",
  "v_fee_allocation_orphans",
  "v_fund_aum_position_health",
  "v_fund_aum_position_status",
  "v_fund_summary_live",
  "v_ib_allocation_orphans",
  "v_investor_kpis",
  "v_itd_returns",
  "v_ledger_reconciliation",
  "v_liquidity_risk",
  "v_live_investor_balances",
  "v_missing_withdrawal_transactions",
  "v_orphaned_positions",
  "v_pending_approvals",
  "v_position_transaction_variance",
  "v_potential_duplicate_profiles",
  "v_transaction_distribution_orphans",
  "v_transaction_sources",
  "v_yield_calculation_health",
  "v_yield_conservation_violations",
  "yield_distribution_conservation_check",
] as const;

export type CompositePKTable = (typeof COMPOSITE_PK_TABLES)[number];

/** Check if a table has a composite PK (cannot use .select("id")) */
export function hasCompositePK(table: TableName): table is CompositePKTable {
  return (COMPOSITE_PK_TABLES as readonly string[]).includes(table);
}

/** Get primary key column names for a table */
export function getPrimaryKeyColumns(table: TableName): string[] {
  const meta = DB_TABLES[table];
  return meta.primaryKey ? [...meta.primaryKey] : [];
}
