/**
 * Database Schema Contracts
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Provides table metadata for runtime validation and IDE support.
 * Regenerate with: npm run contracts:generate
 */

import type { Database } from "@/integrations/supabase/types";

// =============================================================================
// TABLE METADATA
// =============================================================================

export const DB_TABLES = {
  admin_invites: {
    name: "admin_invites" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "email", "expires_at", "id", "invite_code", "used"] as const,
    rlsEnabled: true,
  },
  audit_log: {
    name: "audit_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "action",
      "actor_user",
      "created_at",
      "entity",
      "entity_id",
      "id",
      "meta",
      "new_values",
      "old_values",
    ] as const,
    rlsEnabled: true,
  },
  fee_allocations: {
    name: "fee_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "base_net_income",
      "created_at",
      "created_by",
      "credit_transaction_id",
      "distribution_id",
      "fee_amount",
      "fee_percentage",
      "fees_account_id",
      "fund_id",
      "id",
      "investor_id",
      "is_voided",
      "period_end",
      "period_start",
      "purpose",
    ] as const,
    rlsEnabled: true,
  },
  fund_daily_aum: {
    name: "fund_daily_aum" as const,
    primaryKey: ["id"] as const,
    columns: [
      "as_of_date",
      "aum_date",
      "created_at",
      "created_by",
      "fund_id",
      "gross_yield",
      "id",
      "investor_count",
      "is_month_end",
      "is_voided",
      "net_yield",
      "purpose",
      "source",
      "status",
      "total_aum",
      "updated_at",
      "yield_percentage",
    ] as const,
    rlsEnabled: true,
  },
  funds: {
    name: "funds" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "code",
      "cooling_off_hours",
      "created_at",
      "fund_class",
      "high_water_mark",
      "id",
      "inception_date",
      "large_withdrawal_threshold",
      "lock_period_days",
      "logo_url",
      "max_daily_yield_pct",
      "mgmt_fee_bps",
      "min_investment",
      "min_withdrawal_amount",
      "name",
      "perf_fee_bps",
      "status",
      "strategy",
      "total_aum",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  ib_allocations: {
    name: "ib_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "distribution_id",
      "effective_date",
      "fund_id",
      "ib_fee_amount",
      "ib_investor_id",
      "ib_percentage",
      "id",
      "is_voided",
      "paid_at",
      "paid_by",
      "payout_status",
      "period_end",
      "period_start",
      "purpose",
      "source",
      "source_investor_id",
      "source_net_income",
    ] as const,
    rlsEnabled: true,
  },
  ib_commission_ledger: {
    name: "ib_commission_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fund_id",
      "gross_yield_amount",
      "ib_commission_amount",
      "ib_id",
      "ib_name",
      "ib_percentage",
      "id",
      "is_voided",
      "source_investor_id",
      "source_investor_name",
      "transaction_id",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  investor_fee_schedule: {
    name: "investor_fee_schedule" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "effective_date",
      "end_date",
      "fee_pct",
      "fund_id",
      "ib_pct",
      "id",
      "investor_id",
    ] as const,
    rlsEnabled: true,
  },
  investor_positions: {
    name: "investor_positions" as const,
    primaryKey: null as const,
    columns: [
      "cost_basis",
      "cumulative_yield_earned",
      "current_value",
      "fund_class",
      "fund_id",
      "investor_id",
      "is_active",
      "last_transaction_date",
      "last_yield_crystallization_date",
      "lock_until_date",
      "mgmt_fees_paid",
      "perf_fees_paid",
      "realized_pnl",
      "shares",
      "unrealized_pnl",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_yield_events: {
    name: "investor_yield_events" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "days_in_period",
      "event_date",
      "fee_amount",
      "fee_pct",
      "fund_aum_after",
      "fund_aum_before",
      "fund_id",
      "fund_yield_pct",
      "gross_yield_amount",
      "id",
      "investor_balance",
      "investor_id",
      "investor_share_pct",
      "is_voided",
      "net_yield_amount",
      "period_end",
      "period_start",
      "reference_id",
      "trigger_transaction_id",
      "trigger_type",
      "visibility_scope",
    ] as const,
    rlsEnabled: true,
  },
  notifications: {
    name: "notifications" as const,
    primaryKey: ["id"] as const,
    columns: [
      "body",
      "created_at",
      "data_jsonb",
      "id",
      "priority",
      "read_at",
      "title",
      "type",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  onboarding_submissions: {
    name: "onboarding_submissions" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "id", "investor_id", "status", "submission_data"] as const,
    rlsEnabled: true,
  },
  platform_fee_ledger: {
    name: "platform_fee_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fee_amount",
      "fee_percentage",
      "fund_id",
      "gross_yield_amount",
      "id",
      "investor_id",
      "investor_name",
      "is_voided",
      "transaction_id",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  profiles: {
    name: "profiles" as const,
    primaryKey: ["id"] as const,
    columns: [
      "account_type",
      "created_at",
      "email",
      "entity_type",
      "fee_pct",
      "first_name",
      "ib_commission_source",
      "ib_parent_id",
      "ib_percentage",
      "id",
      "include_in_reporting",
      "is_admin",
      "is_system_account",
      "kyc_status",
      "last_name",
      "onboarding_date",
      "phone",
      "preferences",
      "role",
      "status",
      "totp_enabled",
      "totp_verified",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  qa_entity_manifest: {
    name: "qa_entity_manifest" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "entity_id", "entity_label", "entity_type", "id", "run_tag"] as const,
    rlsEnabled: true,
  },
  qa_scenario_manifest: {
    name: "qa_scenario_manifest" as const,
    primaryKey: ["id"] as const,
    columns: [
      "depends_on_step",
      "executed",
      "executed_at",
      "execution_result",
      "expected_position_delta",
      "expected_success",
      "id",
      "invariants_to_check",
      "params",
      "reference_id",
      "rpc_name",
      "run_tag",
      "scenario_category",
      "scenario_id",
      "step_number",
    ] as const,
    rlsEnabled: true,
  },
  qa_test_results: {
    name: "qa_test_results" as const,
    primaryKey: ["id"] as const,
    columns: [
      "details",
      "duration_ms",
      "executed_at",
      "id",
      "run_tag",
      "status",
      "test_category",
      "test_name",
    ] as const,
    rlsEnabled: true,
  },
  statement_periods: {
    name: "statement_periods" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "id",
      "month",
      "period_end_date",
      "period_name",
      "status",
      "updated_at",
      "year",
    ] as const,
    rlsEnabled: true,
  },
  transactions_v2: {
    name: "transactions_v2" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "approved_at",
      "approved_by",
      "asset",
      "balance_after",
      "balance_before",
      "correction_id",
      "created_at",
      "created_by",
      "fund_class",
      "fund_id",
      "id",
      "investor_id",
      "is_system_generated",
      "is_voided",
      "meta",
      "notes",
      "reference_id",
      "source",
      "transfer_id",
      "tx_date",
      "tx_hash",
      "tx_subtype",
      "type",
      "value_date",
      "visibility_scope",
      "void_reason",
      "voided_at",
      "voided_by",
    ] as const,
    rlsEnabled: true,
  },
  withdrawal_requests: {
    name: "withdrawal_requests" as const,
    primaryKey: ["id"] as const,
    columns: [
      "admin_notes",
      "amount",
      "approved_by",
      "cancelled_by",
      "created_at",
      "fund_id",
      "id",
      "investor_id",
      "processed_at",
      "rejected_by",
      "rejection_reason",
      "request_date",
      "requested_amount",
      "requested_shares",
      "settlement_date",
      "status",
      "tx_hash",
      "updated_at",
      "version",
      "withdrawal_type",
    ] as const,
    rlsEnabled: true,
  },
  yield_allocations: {
    name: "yield_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "adb_share",
      "created_at",
      "distribution_id",
      "fee_amount",
      "fee_pct",
      "fee_transaction_id",
      "fund_id",
      "gross_amount",
      "ib_amount",
      "ib_pct",
      "ib_transaction_id",
      "id",
      "investor_id",
      "net_amount",
      "transaction_id",
    ] as const,
    rlsEnabled: true,
  },
  yield_distributions: {
    name: "yield_distributions" as const,
    primaryKey: ["id"] as const,
    columns: [
      "allocation_count",
      "calculation_method",
      "closing_aum",
      "created_at",
      "created_by",
      "distribution_type",
      "dust_amount",
      "effective_date",
      "fund_id",
      "gross_yield",
      "gross_yield_amount",
      "id",
      "investor_count",
      "is_month_end",
      "is_voided",
      "net_yield",
      "opening_aum",
      "period_end",
      "period_start",
      "previous_aum",
      "purpose",
      "recorded_aum",
      "reference_id",
      "status",
      "summary_json",
      "total_fee_amount",
      "total_fees",
      "total_ib",
      "total_ib_amount",
      "total_net_amount",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_date",
      "yield_percentage",
    ] as const,
    rlsEnabled: true,
  },
} as const;

export type TableName = keyof typeof DB_TABLES;

export type TableColumns<T extends TableName> = (typeof DB_TABLES)[T]["columns"][number];

export type TablePrimaryKey<T extends TableName> = (typeof DB_TABLES)[T]["primaryKey"];

// =============================================================================
// COMPOSITE PRIMARY KEY DETECTION
// =============================================================================

/** Tables with composite primary keys (no single "id" column) */
export const COMPOSITE_PK_TABLES = ["investor_positions"] as const;

export type CompositePKTable = (typeof COMPOSITE_PK_TABLES)[number];

/** Check if a table has a composite PK (cannot use .select("id")) */
export function hasCompositePK(table: TableName): table is CompositePKTable {
  return (COMPOSITE_PK_TABLES as readonly string[]).includes(table);
}

/** Get primary key column names for a table */
export function getPrimaryKeyColumns(table: TableName): string[] {
  const meta = DB_TABLES[table];
  return meta.primaryKey ? [...meta.primaryKey] : [];
}
