/**
 * Database Schema Contracts
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Provides table metadata for runtime validation and IDE support.
 * Regenerate with: npm run contracts:generate
 */

import type { Database } from "@/integrations/supabase/types";

// =============================================================================
// TABLE METADATA
// =============================================================================

export const DB_TABLES = {
  admin_alerts: {
    name: "admin_alerts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "acknowledged_at",
      "acknowledged_by",
      "alert_type",
      "created_at",
      "id",
      "message",
      "metadata",
      "notification_channel",
      "notification_sent_at",
      "related_run_id",
      "severity",
      "title",
    ] as const,
    rlsEnabled: true,
  },
  admin_integrity_runs: {
    name: "admin_integrity_runs" as const,
    primaryKey: ["id"] as const,
    columns: [
      "context",
      "created_by",
      "id",
      "run_at",
      "runtime_ms",
      "scope_fund_id",
      "scope_investor_id",
      "status",
      "triggered_by",
      "violations",
    ] as const,
    rlsEnabled: true,
  },
  assets: {
    name: "assets" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "decimal_places",
      "icon_url",
      "id",
      "is_active",
      "name",
      "symbol",
    ] as const,
    rlsEnabled: true,
  },
  audit_log: {
    name: "audit_log" as const,
    primaryKey: ["id"] as const,
    columns: [
      "action",
      "actor_user",
      "created_at",
      "entity",
      "entity_id",
      "id",
      "meta",
      "new_values",
      "old_values",
    ] as const,
    rlsEnabled: true,
  },
  data_edit_audit: {
    name: "data_edit_audit" as const,
    primaryKey: ["id"] as const,
    columns: [
      "changed_fields",
      "edit_source",
      "edited_at",
      "edited_by",
      "id",
      "import_id",
      "import_related",
      "new_data",
      "old_data",
      "operation",
      "record_id",
      "table_name",
      "voided_record",
    ] as const,
    rlsEnabled: true,
  },
  documents: {
    name: "documents" as const,
    primaryKey: ["id"] as const,
    columns: [
      "checksum",
      "created_at",
      "created_by",
      "created_by_profile_id",
      "fund_id",
      "id",
      "period_end",
      "period_start",
      "storage_path",
      "title",
      "type",
      "user_id",
      "user_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  error_code_metadata: {
    name: "error_code_metadata" as const,
    primaryKey: null,
    columns: [
      "category",
      "created_at",
      "default_message",
      "error_code",
      "is_retryable",
      "severity",
      "ui_action",
      "user_action_hint",
    ] as const,
    rlsEnabled: true,
  },
  fee_allocations: {
    name: "fee_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "base_net_income",
      "created_at",
      "created_by",
      "credit_transaction_id",
      "debit_transaction_id",
      "distribution_id",
      "fee_amount",
      "fee_percentage",
      "fees_account_id",
      "fund_id",
      "id",
      "investor_id",
      "is_voided",
      "period_end",
      "period_start",
      "purpose",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  fund_daily_aum: {
    name: "fund_daily_aum" as const,
    primaryKey: ["id"] as const,
    columns: [
      "as_of_date",
      "aum_date",
      "created_at",
      "created_by",
      "fund_id",
      "id",
      "is_month_end",
      "is_voided",
      "nav_per_share",
      "purpose",
      "source",
      "temporal_lock_bypass",
      "total_aum",
      "total_shares",
      "updated_at",
      "updated_by",
      "void_reason",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  funds: {
    name: "funds" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "code",
      "cooling_off_hours",
      "created_at",
      "fund_class",
      "high_water_mark",
      "id",
      "inception_date",
      "large_withdrawal_threshold",
      "lock_period_days",
      "logo_url",
      "max_daily_yield_pct",
      "mgmt_fee_bps",
      "min_investment",
      "min_withdrawal_amount",
      "name",
      "perf_fee_bps",
      "status",
      "strategy",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  generated_statements: {
    name: "generated_statements" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "fund_names",
      "generated_by",
      "html_content",
      "id",
      "investor_id",
      "pdf_url",
      "period_id",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  global_fee_settings: {
    name: "global_fee_settings" as const,
    primaryKey: null,
    columns: ["description", "setting_key", "updated_at", "updated_by", "value"] as const,
    rlsEnabled: true,
  },
  ib_allocations: {
    name: "ib_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "distribution_id",
      "effective_date",
      "fund_id",
      "ib_fee_amount",
      "ib_investor_id",
      "ib_percentage",
      "id",
      "is_voided",
      "paid_at",
      "paid_by",
      "payout_batch_id",
      "payout_status",
      "period_end",
      "period_id",
      "period_start",
      "purpose",
      "source",
      "source_investor_id",
      "source_net_income",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  ib_commission_ledger: {
    name: "ib_commission_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fund_id",
      "gross_yield_amount",
      "ib_commission_amount",
      "ib_id",
      "ib_name",
      "ib_percentage",
      "id",
      "is_voided",
      "source_investor_id",
      "source_investor_name",
      "transaction_id",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  ib_commission_schedule: {
    name: "ib_commission_schedule" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "effective_date",
      "end_date",
      "fund_id",
      "ib_percentage",
      "id",
      "investor_id",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_daily_balance: {
    name: "investor_daily_balance" as const,
    primaryKey: ["id"] as const,
    columns: [
      "balance_date",
      "created_at",
      "end_of_day_balance",
      "fund_id",
      "id",
      "investor_id",
    ] as const,
    rlsEnabled: true,
  },
  investor_emails: {
    name: "investor_emails" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "email",
      "id",
      "investor_id",
      "is_primary",
      "updated_at",
      "verified",
    ] as const,
    rlsEnabled: true,
  },
  investor_fee_schedule: {
    name: "investor_fee_schedule" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "effective_date",
      "end_date",
      "fee_pct",
      "fund_id",
      "id",
      "investor_id",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  investor_fund_performance: {
    name: "investor_fund_performance" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "fund_name",
      "id",
      "investor_id",
      "itd_additions",
      "itd_beginning_balance",
      "itd_ending_balance",
      "itd_net_income",
      "itd_rate_of_return",
      "itd_redemptions",
      "mtd_additions",
      "mtd_beginning_balance",
      "mtd_ending_balance",
      "mtd_net_income",
      "mtd_rate_of_return",
      "mtd_redemptions",
      "period_id",
      "purpose",
      "qtd_additions",
      "qtd_beginning_balance",
      "qtd_ending_balance",
      "qtd_net_income",
      "qtd_rate_of_return",
      "qtd_redemptions",
      "updated_at",
      "ytd_additions",
      "ytd_beginning_balance",
      "ytd_ending_balance",
      "ytd_net_income",
      "ytd_rate_of_return",
      "ytd_redemptions",
    ] as const,
    rlsEnabled: true,
  },
  investor_position_snapshots: {
    name: "investor_position_snapshots" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "current_value",
      "fund_id",
      "id",
      "investor_id",
      "snapshot_date",
      "snapshot_source",
    ] as const,
    rlsEnabled: true,
  },
  investor_positions: {
    name: "investor_positions" as const,
    primaryKey: null,
    columns: [
      "aum_percentage",
      "cost_basis",
      "cumulative_yield_earned",
      "current_value",
      "fund_class",
      "fund_id",
      "high_water_mark",
      "investor_id",
      "is_active",
      "last_transaction_date",
      "last_yield_crystallization_date",
      "lock_until_date",
      "mgmt_fees_paid",
      "perf_fees_paid",
      "realized_pnl",
      "shares",
      "unrealized_pnl",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  notifications: {
    name: "notifications" as const,
    primaryKey: ["id"] as const,
    columns: [
      "body",
      "created_at",
      "data_jsonb",
      "id",
      "priority",
      "read_at",
      "title",
      "type",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  platform_fee_ledger: {
    name: "platform_fee_ledger" as const,
    primaryKey: ["id"] as const,
    columns: [
      "asset",
      "created_at",
      "created_by",
      "effective_date",
      "fee_amount",
      "fee_percentage",
      "fund_id",
      "gross_yield_amount",
      "id",
      "investor_id",
      "investor_name",
      "is_voided",
      "transaction_id",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_distribution_id",
    ] as const,
    rlsEnabled: true,
  },
  profiles: {
    name: "profiles" as const,
    primaryKey: ["id"] as const,
    columns: [
      "account_type",
      "avatar_url",
      "created_at",
      "email",
      "entity_type",
      "first_name",
      "ib_commission_source",
      "ib_parent_id",
      "id",
      "include_in_reporting",
      "is_admin",
      "is_system_account",
      "kyc_status",
      "last_activity_at",
      "last_name",
      "onboarding_date",
      "phone",
      "preferences",
      "role",
      "status",
      "totp_enabled",
      "totp_verified",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  qa_entity_manifest: {
    name: "qa_entity_manifest" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "entity_id", "entity_label", "entity_type", "id", "run_tag"] as const,
    rlsEnabled: true,
  },
  rate_limit_config: {
    name: "rate_limit_config" as const,
    primaryKey: null,
    columns: [
      "action_type",
      "created_at",
      "description",
      "is_enabled",
      "max_actions",
      "updated_at",
      "window_minutes",
    ] as const,
    rlsEnabled: true,
  },
  report_schedules: {
    name: "report_schedules" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "day_of_month",
      "day_of_week",
      "delivery_method",
      "description",
      "failure_count",
      "filters",
      "formats",
      "frequency",
      "id",
      "is_active",
      "last_run_at",
      "last_run_status",
      "name",
      "next_run_at",
      "parameters",
      "recipient_emails",
      "recipient_user_ids",
      "report_definition_id",
      "run_count",
      "time_of_day",
      "timezone",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
  risk_alerts: {
    name: "risk_alerts" as const,
    primaryKey: ["id"] as const,
    columns: [
      "acknowledged",
      "acknowledged_at",
      "acknowledged_by",
      "actual_value",
      "alert_type",
      "created_at",
      "details",
      "expires_at",
      "fund_id",
      "id",
      "investor_id",
      "message",
      "resolution_notes",
      "resolved",
      "resolved_at",
      "resolved_by",
      "severity",
      "threshold_value",
    ] as const,
    rlsEnabled: true,
  },
  statement_email_delivery: {
    name: "statement_email_delivery" as const,
    primaryKey: ["id"] as const,
    columns: [
      "attempt_count",
      "bounce_type",
      "bounced_at",
      "channel",
      "clicked_at",
      "created_at",
      "created_by",
      "delivered_at",
      "delivery_mode",
      "error_code",
      "error_message",
      "failed_at",
      "id",
      "investor_id",
      "last_attempt_at",
      "locked_at",
      "locked_by",
      "metadata",
      "opened_at",
      "period_id",
      "provider",
      "provider_message_id",
      "recipient_email",
      "retry_count",
      "sent_at",
      "statement_id",
      "status",
      "subject",
      "updated_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  statement_periods: {
    name: "statement_periods" as const,
    primaryKey: ["id"] as const,
    columns: [
      "created_at",
      "created_by",
      "finalized_at",
      "finalized_by",
      "id",
      "month",
      "notes",
      "period_end_date",
      "period_name",
      "status",
      "updated_at",
      "year",
    ] as const,
    rlsEnabled: true,
  },
  statements: {
    name: "statements" as const,
    primaryKey: ["id"] as const,
    columns: [
      "additions",
      "asset_code",
      "begin_balance",
      "created_at",
      "end_balance",
      "id",
      "investor_id",
      "investor_profile_id",
      "net_income",
      "period_month",
      "period_year",
      "rate_of_return_itd",
      "rate_of_return_mtd",
      "rate_of_return_qtd",
      "rate_of_return_ytd",
      "redemptions",
      "storage_path",
    ] as const,
    rlsEnabled: true,
  },
  support_tickets: {
    name: "support_tickets" as const,
    primaryKey: ["id"] as const,
    columns: [
      "assigned_admin_id",
      "attachments",
      "category",
      "created_at",
      "id",
      "messages_jsonb",
      "priority",
      "status",
      "subject",
      "updated_at",
      "user_id",
    ] as const,
    rlsEnabled: true,
  },
  system_config: {
    name: "system_config" as const,
    primaryKey: null,
    columns: ["description", "key", "updated_at", "updated_by", "value"] as const,
    rlsEnabled: true,
  },
  transactions_v2: {
    name: "transactions_v2" as const,
    primaryKey: ["id"] as const,
    columns: [
      "amount",
      "approved_at",
      "approved_by",
      "asset",
      "balance_after",
      "balance_before",
      "correction_id",
      "created_at",
      "created_by",
      "distribution_id",
      "fund_class",
      "fund_id",
      "id",
      "investor_id",
      "is_system_generated",
      "is_voided",
      "meta",
      "notes",
      "purpose",
      "reference_id",
      "source",
      "transfer_id",
      "tx_date",
      "tx_hash",
      "tx_subtype",
      "type",
      "value_date",
      "visibility_scope",
      "void_reason",
      "voided_at",
      "voided_by",
      "voided_by_profile_id",
    ] as const,
    rlsEnabled: true,
  },
  user_roles: {
    name: "user_roles" as const,
    primaryKey: ["id"] as const,
    columns: ["created_at", "id", "role", "user_id"] as const,
    rlsEnabled: true,
  },
  withdrawal_requests: {
    name: "withdrawal_requests" as const,
    primaryKey: ["id"] as const,
    columns: [
      "admin_notes",
      "approved_amount",
      "approved_at",
      "approved_by",
      "approved_shares",
      "cancellation_reason",
      "cancelled_at",
      "cancelled_by",
      "created_by",
      "earliest_processing_at",
      "fund_class",
      "fund_id",
      "id",
      "investor_id",
      "notes",
      "processed_amount",
      "processed_at",
      "rejected_at",
      "rejected_by",
      "rejection_reason",
      "request_date",
      "requested_amount",
      "requested_shares",
      "settlement_date",
      "status",
      "tx_hash",
      "updated_at",
      "version",
      "withdrawal_type",
    ] as const,
    rlsEnabled: true,
  },
  yield_allocations: {
    name: "yield_allocations" as const,
    primaryKey: ["id"] as const,
    columns: [
      "adb_share",
      "created_at",
      "distribution_id",
      "fee_amount",
      "fee_pct",
      "fee_transaction_id",
      "fund_id",
      "gross_amount",
      "ib_amount",
      "ib_pct",
      "ib_transaction_id",
      "id",
      "investor_id",
      "is_voided",
      "net_amount",
      "ownership_pct",
      "position_value_at_calc",
      "transaction_id",
    ] as const,
    rlsEnabled: true,
  },
  yield_distributions: {
    name: "yield_distributions" as const,
    primaryKey: ["id"] as const,
    columns: [
      "allocation_count",
      "aum_record_id",
      "calculation_method",
      "closing_aum",
      "consolidated_into_id",
      "created_at",
      "created_by",
      "distribution_type",
      "dust_amount",
      "dust_receiver_id",
      "effective_date",
      "fund_id",
      "gross_yield",
      "gross_yield_amount",
      "id",
      "investor_count",
      "is_month_end",
      "is_voided",
      "net_yield",
      "opening_aum",
      "parent_distribution_id",
      "period_end",
      "period_start",
      "previous_aum",
      "purpose",
      "reason",
      "recorded_aum",
      "reference_id",
      "snapshot_time",
      "status",
      "summary_json",
      "total_fee_amount",
      "total_fees",
      "total_ib",
      "total_ib_amount",
      "total_net_amount",
      "void_reason",
      "voided_at",
      "voided_by",
      "yield_date",
      "yield_percentage",
    ] as const,
    rlsEnabled: true,
  },
  yield_rate_sanity_config: {
    name: "yield_rate_sanity_config" as const,
    primaryKey: ["id"] as const,
    columns: [
      "alert_threshold_pct",
      "created_at",
      "fund_id",
      "id",
      "max_daily_yield_pct",
      "min_daily_yield_pct",
      "updated_at",
    ] as const,
    rlsEnabled: true,
  },
} as const;

export type TableName = keyof typeof DB_TABLES;

export type TableColumns<T extends TableName> = (typeof DB_TABLES)[T]["columns"][number];

export type TablePrimaryKey<T extends TableName> = (typeof DB_TABLES)[T]["primaryKey"];

// =============================================================================
// COMPOSITE PRIMARY KEY DETECTION
// =============================================================================

/** Tables with composite primary keys (no single "id" column) */
export const COMPOSITE_PK_TABLES = [
  "error_code_metadata",
  "global_fee_settings",
  "investor_positions",
  "rate_limit_config",
  "system_config",
] as const;

export type CompositePKTable = (typeof COMPOSITE_PK_TABLES)[number];

/** Check if a table has a composite PK (cannot use .select("id")) */
export function hasCompositePK(table: TableName): table is CompositePKTable {
  return (COMPOSITE_PK_TABLES as readonly string[]).includes(table);
}

/** Get primary key column names for a table */
export function getPrimaryKeyColumns(table: TableName): string[] {
  const meta = DB_TABLES[table];
  return meta.primaryKey ? [...meta.primaryKey] : [];
}
