/**
 * RPC Function Signatures
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Provides compile-time and runtime verification of RPC calls.
 * Regenerate with: npm run contracts:generate
 */

import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

// =============================================================================
// RPC FUNCTION REGISTRY
// =============================================================================

type RPCFunctions = Database["public"]["Functions"];
export type RPCFunctionName = keyof RPCFunctions;

/** All registered RPC function names */
export const RPC_FUNCTIONS = [
  "_resolve_investor_fee_pct",
  "_resolve_investor_ib_pct",
  "_v5_check_distribution_uniqueness",
  "acquire_delivery_batch",
  "acquire_position_lock",
  "acquire_withdrawal_lock",
  "acquire_yield_lock",
  "add_fund_to_investor",
  "adjust_investor_position",
  "apply_transaction_with_crystallization",
  "apply_segmented_yield_distribution",
  "apply_segmented_yield_distribution_v5",
  "approve_and_complete_withdrawal",
  "approve_withdrawal",
  "assert_integrity_or_raise",
  "backfill_balance_chain_fix",
  "batch_reconcile_all_positions",
  "build_error_response",
  "build_success_response",
  "calc_avg_daily_balance",
  "calculate_position_at_date_fix",
  "can_access_investor",
  "can_access_notification",
  "can_insert_notification",
  "can_withdraw",
  "cancel_delivery",
  "cancel_withdrawal_by_admin",
  "cancel_withdrawal_by_investor",
  "check_all_funds_transaction_aum",
  "check_aum_position_health",
  "check_aum_reconciliation",
  "check_duplicate_ib_allocations",
  "check_duplicate_transaction_refs",
  "check_is_admin",
  "check_platform_data_integrity",
  "check_transaction_sources",
  "cleanup_dormant_positions",
  "complete_withdrawal",
  "compute_jsonb_delta",
  "compute_position_from_ledger",
  "compute_profile_role",
  "create_daily_position_snapshot",
  "create_integrity_alert",
  "create_withdrawal_request",
  
  "current_user_is_admin_or_owner",
  "delete_transaction",
  "delete_withdrawal",
  "dispatch_report_delivery_run",
  "edit_transaction",
  "ensure_admin",
  "export_investor_data",
  "finalize_month_yield",
  "finalize_statement_period",
  "fix_yield_distribution_investor_count",
  "force_delete_investor",
  "generate_document_path",
  "generate_statement_path",
  "get_active_funds_summary",
  "get_admin_stats",
  "get_admin_name",
  "get_all_dust_tolerances",
  "get_aum_position_reconciliation",
  "get_available_balance",
  "get_delivery_stats",
  "get_dust_tolerance_for_fund",
  "get_fund_aum_as_of",
  "get_fund_base_asset",
  "get_fund_composition",
  "get_fund_net_flows",
  "get_fund_positions_sum",
  "get_fund_summary",
  "get_funds_aum_snapshot",
  "get_funds_daily_flows",
  "get_funds_with_aum",
  "get_health_trend",
  "get_ib_parent_candidates",
  "get_ib_referral_count",
  "get_ib_referral_detail",
  "get_ib_referrals",
  "get_all_investors_summary",
  "get_investor_cumulative_yield",
  "get_investor_fee_pct",
  "get_investor_ib_pct",
  "get_investor_reports_v2",
  "get_investor_yield_summary",
  "get_latest_health_status",
  "get_monthly_platform_aum",
  "get_period_delivery_stats",
  "get_platform_flow_metrics",
  "get_platform_stats",
  "get_position_reconciliation",
  "get_reporting_eligible_investors",
  "get_schema_dump",
  "get_statement_period_summary",
  "get_statement_signed_url",
  "get_system_mode",
  "get_user_admin_status",
  "get_void_aum_impact",
  "get_void_transaction_impact",
  "get_void_yield_impact",
  "has_role",
  "has_super_admin_role",
  "initialize_all_hwm_values",
  "initialize_null_crystallization_dates",
  "internal_route_to_fees",
  "is_admin",
  "is_admin_for_jwt",
  "is_admin_safe",
  "is_canonical_rpc",
  "is_import_enabled",
  "is_period_locked",
  "is_super_admin",
  "is_within_edit_window",
  "is_yield_period_closed",
  "get_paged_audit_logs",
  "get_paged_notifications",
  "get_paged_investor_summaries",
  "log_audit_event",
  "log_financial_operation",
  "log_ledger_mismatches",
  "log_security_event",
  "log_withdrawal_action",
  "mark_delivery_result",
  "mark_sent_manually",
  "merge_duplicate_profiles",
  "nightly_aum_reconciliation",
  "parse_platform_error",
  "populate_investor_fund_performance",
  "preview_daily_yield_to_fund_v3",
  "preview_merge_duplicate_profiles",
  "preview_segmented_yield_distribution_v5",
  "purge_fund_hard",
  "qa_fees_account_id",
  "qa_fund_id",
  "qa_investor_id",
  "queue_statement_deliveries",
  "raise_platform_error",
  "rebuild_position_from_ledger",
  "recalculate_fund_aum_for_date",
  "recompute_investor_position",
  "recompute_investor_positions_for_investor",
  "reconcile_all_positions",
  "reject_withdrawal",
  "reopen_yield_period",
  "repair_all_positions",
  "requeue_stale_sending",
  "require_admin",
  "require_super_admin",
  "retry_delivery",
  "route_withdrawal_to_fees",
  "run_comprehensive_health_check",
  "run_daily_health_check",
  "run_integrity_check",
  "run_integrity_pack",
  "run_invariant_checks",
  "set_canonical_rpc",
  "start_processing_withdrawal",
  "system_health_check",
  "unvoid_transaction",
  "unvoid_transactions_bulk",
  "update_admin_role",
  "update_dust_tolerance",
  "update_fund_aum_baseline",
  "update_investor_aum_percentages",
  "update_transaction",
  "update_user_profile_secure",
  "update_withdrawal",
  "validate_aum_against_positions",
  "validate_aum_against_positions_at_date",
  "validate_aum_matches_positions",
  "validate_aum_matches_positions_strict",
  "validate_pre_yield_aum",
  "validate_transaction_aum_exists",
  "validate_withdrawal_transition",
  "validate_yield_distribution_prerequisites",
  "validate_yield_parameters",
  "validate_yield_rate_sanity",
  "verify_yield_distribution_balance",
  "void_and_reissue_full_exit",
  "void_and_reissue_transaction",
  "void_completed_withdrawal",
  "void_transaction",
  "void_transactions_bulk",
  "void_yield_distribution",
  "unvoid_yield_distribution",
] as const;

// =============================================================================
// RPC SIGNATURES METADATA
// =============================================================================

export const RPC_SIGNATURES = {
  _resolve_investor_fee_pct: {
    name: "_resolve_investor_fee_pct" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_effective_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  _resolve_investor_ib_pct: {
    name: "_resolve_investor_ib_pct" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_effective_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  _v5_check_distribution_uniqueness: {
    name: "_v5_check_distribution_uniqueness" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_period_end", "p_purpose"] as const,
    optionalParams: [] as const,
  },
  acquire_delivery_batch: {
    name: "acquire_delivery_batch" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_batch_size", "p_channel", "p_worker_id"] as const,
  },
  acquire_position_lock: {
    name: "acquire_position_lock" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  acquire_withdrawal_lock: {
    name: "acquire_withdrawal_lock" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [] as const,
  },
  acquire_yield_lock: {
    name: "acquire_yield_lock" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  add_fund_to_investor: {
    name: "add_fund_to_investor" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_cost_basis", "p_initial_shares"] as const,
  },
  adjust_investor_position: {
    name: "adjust_investor_position" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id", "p_reason", "p_tx_date"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  apply_transaction_with_crystallization: {
    name: "apply_transaction_with_crystallization" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_fund_id",
      "p_investor_id",
      "p_reference_id",
      "p_tx_date",
      "p_tx_type",
    ] as const,
    optionalParams: ["p_notes", "p_purpose"] as const,
  },
  apply_segmented_yield_distribution: {
    name: "apply_segmented_yield_distribution" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id", "p_period_end", "p_recorded_aum"] as const,
    optionalParams: ["p_admin_id", "p_distribution_date", "p_purpose"] as const,
  },
  apply_segmented_yield_distribution_v5: {
    name: "apply_segmented_yield_distribution_v5" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id", "p_period_end", "p_recorded_aum", "p_purpose"] as const,
    optionalParams: ["p_opening_aum", "p_admin_id", "p_distribution_date"] as const,
  },
  approve_and_complete_withdrawal: {
    name: "approve_and_complete_withdrawal" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [
      "p_admin_notes",
      "p_is_full_exit",
      "p_processed_amount",
      "p_send_precision",
      "p_tx_hash",
    ] as const,
  },
  approve_withdrawal: {
    name: "approve_withdrawal" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: ["p_admin_notes", "p_approved_amount"] as const,
  },
  assert_integrity_or_raise: {
    name: "assert_integrity_or_raise" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_context", "p_scope_fund_id", "p_scope_investor_id"] as const,
  },
  backfill_balance_chain_fix: {
    name: "backfill_balance_chain_fix" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  batch_reconcile_all_positions: {
    name: "batch_reconcile_all_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  build_error_response: {
    name: "build_error_response" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_code"] as const,
    optionalParams: ["p_details"] as const,
  },
  build_success_response: {
    name: "build_success_response" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_data", "p_message"] as const,
  },
  calc_avg_daily_balance: {
    name: "calc_avg_daily_balance" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id", "p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  calculate_position_at_date_fix: {
    name: "calculate_position_at_date_fix" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  can_access_investor: {
    name: "can_access_investor" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["investor_uuid"] as const,
    optionalParams: [] as const,
  },
  can_access_notification: {
    name: "can_access_notification" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["notification_id"] as const,
    optionalParams: [] as const,
  },
  can_insert_notification: {
    name: "can_insert_notification" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  can_withdraw: {
    name: "can_withdraw" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  cancel_delivery: {
    name: "cancel_delivery" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: [] as const,
  },
  cancel_withdrawal_by_admin: {
    name: "cancel_withdrawal_by_admin" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_request_id"] as const,
    optionalParams: ["p_admin_notes"] as const,
  },
  cancel_withdrawal_by_investor: {
    name: "cancel_withdrawal_by_investor" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id", "p_request_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
  check_all_funds_transaction_aum: {
    name: "check_all_funds_transaction_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_tx_date"] as const,
    optionalParams: [] as const,
  },
  check_aum_position_health: {
    name: "check_aum_position_health" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_aum_reconciliation: {
    name: "check_aum_reconciliation" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date", "p_fund_id"] as const,
    optionalParams: ["p_tolerance_pct"] as const,
  },
  check_duplicate_ib_allocations: {
    name: "check_duplicate_ib_allocations" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_duplicate_transaction_refs: {
    name: "check_duplicate_transaction_refs" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_is_admin: {
    name: "check_is_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["user_id"] as const,
    optionalParams: [] as const,
  },
  check_platform_data_integrity: {
    name: "check_platform_data_integrity" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_transaction_sources: {
    name: "check_transaction_sources" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  cleanup_dormant_positions: {
    name: "cleanup_dormant_positions" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  complete_withdrawal: {
    name: "complete_withdrawal" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_closing_aum", "p_request_id"] as const,
    optionalParams: ["p_admin_notes", "p_event_ts", "p_transaction_hash"] as const,
  },
  compute_jsonb_delta: {
    name: "compute_jsonb_delta" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_new", "p_old"] as const,
    optionalParams: [] as const,
  },
  compute_position_from_ledger: {
    name: "compute_position_from_ledger" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_as_of"] as const,
  },
  compute_profile_role: {
    name: "compute_profile_role" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_account_type", "p_is_admin", "p_user_id"] as const,
    optionalParams: [] as const,
  },
  create_daily_position_snapshot: {
    name: "create_daily_position_snapshot" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_fund_id", "p_snapshot_date"] as const,
  },
  create_integrity_alert: {
    name: "create_integrity_alert" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_alert_type", "p_message", "p_severity", "p_title"] as const,
    optionalParams: ["p_metadata"] as const,
  },
  create_withdrawal_request: {
    name: "create_withdrawal_request" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_notes", "p_type"] as const,
  },
  current_user_is_admin_or_owner: {
    name: "current_user_is_admin_or_owner" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["check_user_id"] as const,
    optionalParams: [] as const,
  },
  delete_transaction: {
    name: "delete_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_confirmation", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  delete_withdrawal: {
    name: "delete_withdrawal" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_withdrawal_id"] as const,
    optionalParams: ["p_hard_delete"] as const,
  },
  dispatch_report_delivery_run: {
    name: "dispatch_report_delivery_run" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_channel"] as const,
  },
  edit_transaction: {
    name: "edit_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_transaction_id"] as const,
    optionalParams: ["p_notes", "p_reference_id", "p_tx_date", "p_tx_hash"] as const,
  },
  ensure_admin: {
    name: "ensure_admin" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  export_investor_data: {
    name: "export_investor_data" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  finalize_month_yield: {
    name: "finalize_month_yield" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_period_month", "p_period_year"] as const,
    optionalParams: [] as const,
  },
  finalize_statement_period: {
    name: "finalize_statement_period" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_period_id"] as const,
    optionalParams: [] as const,
  },
  fix_yield_distribution_investor_count: {
    name: "fix_yield_distribution_investor_count" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_distribution_id"] as const,
    optionalParams: [] as const,
  },
  force_delete_investor: {
    name: "force_delete_investor" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  generate_document_path: {
    name: "generate_document_path" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["document_type", "filename", "user_id"] as const,
    optionalParams: [] as const,
  },
  generate_statement_path: {
    name: "generate_statement_path" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["month", "user_id", "year"] as const,
    optionalParams: ["fund_code"] as const,
  },
  get_active_funds_summary: {
    name: "get_active_funds_summary" as const,
    returnType: "any[];",
    returnsSet: true,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_all_investors_summary: {
    name: "get_all_investors_summary" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_admin_stats: {
    name: "get_admin_stats" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_platform_flow_metrics: {
    name: "get_platform_flow_metrics" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: ["p_days"] as const,
  },
  get_period_delivery_stats: {
    name: "get_period_delivery_stats" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  purge_fund_hard: {
    name: "purge_fund_hard" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_admin_name: {
    name: "get_admin_name" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["admin_id"] as const,
    optionalParams: [] as const,
  },
  get_all_dust_tolerances: {
    name: "get_all_dust_tolerances" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_aum_position_reconciliation: {
    name: "get_aum_position_reconciliation" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_date"] as const,
  },
  get_available_balance: {
    name: "get_available_balance" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_delivery_stats: {
    name: "get_delivery_stats" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_dust_tolerance_for_fund: {
    name: "get_dust_tolerance_for_fund" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_fund_aum_as_of: {
    name: "get_fund_aum_as_of" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date", "p_fund_id"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  get_fund_base_asset: {
    name: "get_fund_base_asset" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_fund_composition: {
    name: "get_fund_composition" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_date"] as const,
  },
  get_fund_net_flows: {
    name: "get_fund_net_flows" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_end_date", "p_fund_id", "p_start_date"] as const,
    optionalParams: [] as const,
  },
  get_fund_positions_sum: {
    name: "get_fund_positions_sum" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_fund_summary: {
    name: "get_fund_summary" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_funds_aum_snapshot: {
    name: "get_funds_aum_snapshot" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  get_funds_daily_flows: {
    name: "get_funds_daily_flows" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_date"] as const,
    optionalParams: [] as const,
  },
  get_paged_audit_logs: {
    name: "get_paged_audit_logs" as const,
    returnType: "table" as const,
    returnsSet: true,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: ["p_limit", "p_offset", "p_entity", "p_action", "p_actor_id"] as const,
  },
  get_paged_notifications: {
    name: "get_paged_notifications" as const,
    returnType: "table" as const,
    returnsSet: true,
    securityDefiner: true,
    requiredParams: ["p_user_id"] as const,
    optionalParams: ["p_limit", "p_offset"] as const,
  },
  get_paged_investor_summaries: {
    name: "get_paged_investor_summaries" as const,
    returnType: "table" as const,
    returnsSet: true,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: ["p_limit", "p_offset", "p_status"] as const,
  },
  get_funds_with_aum: {
    name: "get_funds_with_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_health_trend: {
    name: "get_health_trend" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_days"] as const,
  },
  get_ib_parent_candidates: {
    name: "get_ib_parent_candidates" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_exclude_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referral_count: {
    name: "get_ib_referral_count" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_ib_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referral_detail: {
    name: "get_ib_referral_detail" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_ib_id", "p_referral_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referrals: {
    name: "get_ib_referrals" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_ib_id"] as const,
    optionalParams: ["p_limit", "p_offset"] as const,
  },
  get_investor_cumulative_yield: {
    name: "get_investor_cumulative_yield" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_investor_fee_pct: {
    name: "get_investor_fee_pct" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_effective_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_investor_ib_pct: {
    name: "get_investor_ib_pct" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_effective_date"] as const,
  },
  get_investor_reports_v2: {
    name: "get_investor_reports_v2" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_investor_yield_summary: {
    name: "get_investor_yield_summary" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id"] as const,
    optionalParams: ["p_month", "p_year"] as const,
  },
  get_latest_health_status: {
    name: "get_latest_health_status" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_monthly_platform_aum: {
    name: "get_monthly_platform_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_platform_stats: {
    name: "get_platform_stats" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_position_reconciliation: {
    name: "get_position_reconciliation" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_as_of_date", "p_fund_id"] as const,
  },
  get_reporting_eligible_investors: {
    name: "get_reporting_eligible_investors" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_schema_dump: {
    name: "get_schema_dump" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_statement_period_summary: {
    name: "get_statement_period_summary" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_statement_signed_url: {
    name: "get_statement_signed_url" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_storage_path"] as const,
    optionalParams: ["p_expires_in"] as const,
  },
  get_system_mode: {
    name: "get_system_mode" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_user_admin_status: {
    name: "get_user_admin_status" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["user_id"] as const,
    optionalParams: [] as const,
  },
  get_void_aum_impact: {
    name: "get_void_aum_impact" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_record_id"] as const,
    optionalParams: [] as const,
  },
  get_void_transaction_impact: {
    name: "get_void_transaction_impact" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  get_void_yield_impact: {
    name: "get_void_yield_impact" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_distribution_id"] as const,
    optionalParams: [] as const,
  },
  has_role: {
    name: "has_role" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["_role", "_user_id"] as const,
    optionalParams: [] as const,
  },
  has_super_admin_role: {
    name: "has_super_admin_role" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  initialize_all_hwm_values: {
    name: "initialize_all_hwm_values" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  initialize_null_crystallization_dates: {
    name: "initialize_null_crystallization_dates" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  internal_route_to_fees: {
    name: "internal_route_to_fees" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_effective_date",
      "p_from_investor_id",
      "p_fund_id",
      "p_reason",
    ] as const,
    optionalParams: ["p_transfer_id"] as const,
  },
  is_admin: {
    name: "is_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  is_admin_for_jwt: {
    name: "is_admin_for_jwt" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_admin_safe: {
    name: "is_admin_safe" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_canonical_rpc: {
    name: "is_canonical_rpc" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_import_enabled: {
    name: "is_import_enabled" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_period_locked: {
    name: "is_period_locked" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: [] as const,
  },
  is_super_admin: {
    name: "is_super_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  is_within_edit_window: {
    name: "is_within_edit_window" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_created_at"] as const,
    optionalParams: [] as const,
  },
  is_yield_period_closed: {
    name: "is_yield_period_closed" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_month", "p_purpose", "p_year"] as const,
    optionalParams: [] as const,
  },
  log_audit_event: {
    name: "log_audit_event" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_entity"] as const,
    optionalParams: ["p_entity_id", "p_meta", "p_new_values", "p_old_values"] as const,
  },
  log_financial_operation: {
    name: "log_financial_operation" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_entity", "p_entity_id"] as const,
    optionalParams: ["p_meta", "p_new_values", "p_old_values"] as const,
  },
  log_ledger_mismatches: {
    name: "log_ledger_mismatches" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  log_security_event: {
    name: "log_security_event" as const,
    returnType: "string;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_event_type", "p_severity"] as const,
    optionalParams: ["p_details", "p_user_id"] as const,
  },
  log_withdrawal_action: {
    name: "log_withdrawal_action" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_request_id"] as const,
    optionalParams: ["p_meta"] as const,
  },
  mark_delivery_result: {
    name: "mark_delivery_result" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id", "p_success"] as const,
    optionalParams: ["p_error_code", "p_error_message", "p_provider_message_id"] as const,
  },
  mark_sent_manually: {
    name: "mark_sent_manually" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: ["p_note"] as const,
  },
  merge_duplicate_profiles: {
    name: "merge_duplicate_profiles" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_keep_id", "p_merge_id"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  nightly_aum_reconciliation: {
    name: "nightly_aum_reconciliation" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  parse_platform_error: {
    name: "parse_platform_error" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_message"] as const,
    optionalParams: [] as const,
  },
  populate_investor_fund_performance: {
    name: "populate_investor_fund_performance" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_investor_id"] as const,
  },
  preview_daily_yield_to_fund_v3: {
    name: "preview_daily_yield_to_fund_v3" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_new_aum", "p_yield_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  preview_merge_duplicate_profiles: {
    name: "preview_merge_duplicate_profiles" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_keep_profile_id", "p_merge_profile_id"] as const,
    optionalParams: [] as const,
  },
  preview_segmented_yield_distribution_v5: {
    name: "preview_segmented_yield_distribution_v5" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_period_end", "p_recorded_aum"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  qa_fees_account_id: {
    name: "qa_fees_account_id" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  qa_fund_id: {
    name: "qa_fund_id" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_asset"] as const,
    optionalParams: [] as const,
  },
  qa_investor_id: {
    name: "qa_investor_id" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_key"] as const,
    optionalParams: [] as const,
  },
  queue_statement_deliveries: {
    name: "queue_statement_deliveries" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_channel", "p_fund_id", "p_investor_ids"] as const,
  },
  raise_platform_error: {
    name: "raise_platform_error" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_code"] as const,
    optionalParams: ["p_details"] as const,
  },
  rebuild_position_from_ledger: {
    name: "rebuild_position_from_ledger" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_investor_id", "p_reason"] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  recalculate_fund_aum_for_date: {
    name: "recalculate_fund_aum_for_date" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: ["p_actor_id", "p_purpose"] as const,
  },
  recompute_investor_position: {
    name: "recompute_investor_position" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  recompute_investor_positions_for_investor: {
    name: "recompute_investor_positions_for_investor" as const,
    returnType: "undefined;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id"] as const,
    optionalParams: [] as const,
  },
  reconcile_all_positions: {
    name: "reconcile_all_positions" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  reject_withdrawal: {
    name: "reject_withdrawal" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_request_id"] as const,
    optionalParams: ["p_admin_notes"] as const,
  },
  reopen_yield_period: {
    name: "reopen_yield_period" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_month", "p_purpose", "p_reason", "p_year"] as const,
    optionalParams: [] as const,
  },
  repair_all_positions: {
    name: "repair_all_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  requeue_stale_sending: {
    name: "requeue_stale_sending" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_minutes"] as const,
  },
  require_admin: {
    name: "require_admin" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_operation"] as const,
  },
  require_super_admin: {
    name: "require_super_admin" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_actor_id", "p_operation"] as const,
    optionalParams: [] as const,
  },
  retry_delivery: {
    name: "retry_delivery" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: [] as const,
  },
  route_withdrawal_to_fees: {
    name: "route_withdrawal_to_fees" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_actor_id", "p_request_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
  run_comprehensive_health_check: {
    name: "run_comprehensive_health_check" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  run_daily_health_check: {
    name: "run_daily_health_check" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  run_integrity_check: {
    name: "run_integrity_check" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_scope_fund_id", "p_scope_investor_id"] as const,
  },
  run_integrity_pack: {
    name: "run_integrity_pack" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_scope_fund_id", "p_scope_investor_id"] as const,
  },
  run_invariant_checks: {
    name: "run_invariant_checks" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  set_canonical_rpc: {
    name: "set_canonical_rpc" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["enabled"] as const,
  },
  start_processing_withdrawal: {
    name: "start_processing_withdrawal" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [
      "p_admin_notes",
      "p_processed_amount",
      "p_settlement_date",
      "p_tx_hash",
    ] as const,
  },
  system_health_check: {
    name: "system_health_check" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  unvoid_transaction: {
    name: "unvoid_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  unvoid_transactions_bulk: {
    name: "unvoid_transactions_bulk" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_ids"] as const,
    optionalParams: [] as const,
  },
  update_admin_role: {
    name: "update_admin_role" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_new_role", "p_target_user_id"] as const,
    optionalParams: [] as const,
  },
  update_dust_tolerance: {
    name: "update_dust_tolerance" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_asset", "p_tolerance"] as const,
    optionalParams: [] as const,
  },
  update_fund_aum_baseline: {
    name: "update_fund_aum_baseline" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_new_baseline"] as const,
    optionalParams: [] as const,
  },
  update_investor_aum_percentages: {
    name: "update_investor_aum_percentages" as const,
    returnType: "number;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  update_transaction: {
    name: "update_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_transaction_id", "p_updates"] as const,
    optionalParams: [] as const,
  },
  update_user_profile_secure: {
    name: "update_user_profile_secure" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: ["p_first_name", "p_last_name", "p_phone", "p_status"] as const,
  },
  update_withdrawal: {
    name: "update_withdrawal" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_withdrawal_id"] as const,
    optionalParams: ["p_notes", "p_reason", "p_requested_amount", "p_withdrawal_type"] as const,
  },
  validate_aum_against_positions: {
    name: "validate_aum_against_positions" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum_value", "p_fund_id"] as const,
    optionalParams: ["p_context", "p_max_deviation_pct"] as const,
  },
  validate_aum_against_positions_at_date: {
    name: "validate_aum_against_positions_at_date" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum_value", "p_event_date", "p_fund_id"] as const,
    optionalParams: ["p_context", "p_max_deviation_pct"] as const,
  },
  validate_aum_matches_positions: {
    name: "validate_aum_matches_positions" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_aum_date", "p_purpose", "p_tolerance_pct"] as const,
  },
  validate_aum_matches_positions_strict: {
    name: "validate_aum_matches_positions_strict" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_aum_date", "p_purpose"] as const,
  },
  validate_pre_yield_aum: {
    name: "validate_pre_yield_aum" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_tolerance_percentage"] as const,
  },
  validate_transaction_aum_exists: {
    name: "validate_transaction_aum_exists" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_tx_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  validate_withdrawal_transition: {
    name: "validate_withdrawal_transition" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_current_status", "p_new_status"] as const,
    optionalParams: [] as const,
  },
  validate_yield_distribution_prerequisites: {
    name: "validate_yield_distribution_prerequisites" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: ["p_admin_id", "p_aum_tolerance_pct", "p_auto_sync", "p_purpose"] as const,
  },
  validate_yield_parameters: {
    name: "validate_yield_parameters" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct", "p_purpose", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  validate_yield_rate_sanity: {
    name: "validate_yield_rate_sanity" as const,
    returnType: "boolean;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_yield_pct"] as const,
    optionalParams: ["p_context", "p_fund_id"] as const,
  },
  verify_yield_distribution_balance: {
    name: "verify_yield_distribution_balance" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  void_and_reissue_full_exit: {
    name: "void_and_reissue_full_exit" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_transaction_id", "p_new_amount", "p_admin_id", "p_reason"] as const,
    optionalParams: ["p_send_precision"] as const,
  },
  void_and_reissue_transaction: {
    name: "void_and_reissue_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_new_amount", "p_new_date", "p_original_tx_id"] as const,
    optionalParams: ["p_closing_aum", "p_new_notes", "p_new_tx_hash", "p_reason"] as const,
  },
  void_transaction: {
    name: "void_transaction" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  void_transactions_bulk: {
    name: "void_transactions_bulk" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_ids"] as const,
    optionalParams: [] as const,
  },
  void_yield_distribution: {
    name: "void_yield_distribution" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_distribution_id"] as const,
    optionalParams: ["p_reason", "p_void_crystals"] as const,
  },
  unvoid_yield_distribution: {
    name: "unvoid_yield_distribution" as const,
    returnType: "Json;",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_distribution_id", "p_reason"] as const,
    optionalParams: [] as const,
  },
} as const;

// =============================================================================
// TYPE HELPERS
// =============================================================================

/** Get required parameters for an RPC function */
export type RPCRequiredParams<T extends RPCFunctionName> = T extends keyof typeof RPC_SIGNATURES
  ? (typeof RPC_SIGNATURES)[T]["requiredParams"][number]
  : never;

/** Get optional parameters for an RPC function */
export type RPCOptionalParams<T extends RPCFunctionName> = T extends keyof typeof RPC_SIGNATURES
  ? (typeof RPC_SIGNATURES)[T]["optionalParams"][number]
  : never;

/** Validate that an RPC function exists */
export function isValidRPCFunction(name: string): name is RPCFunctionName {
  return (RPC_FUNCTIONS as readonly string[]).includes(name);
}

/** Get signature metadata for an RPC function */
export function getRPCSignature<T extends RPCFunctionName>(name: T) {
  if (!isValidRPCFunction(name)) {
    throw new Error(`Unknown RPC function: ${name}`);
  }
  return RPC_SIGNATURES[name as keyof typeof RPC_SIGNATURES];
}

// =============================================================================
// CANONICAL MUTATION RPCS
// =============================================================================
// These are the ONLY RPCs that should be used for mutations

export const CANONICAL_MUTATION_RPCS = {
  /** V6: All deposits/withdrawals go through the unified transaction RPC */
  DEPOSIT: "apply_investor_transaction",
  /** V6: All deposits/withdrawals go through the unified transaction RPC */
  WITHDRAWAL: "apply_investor_transaction",
  /** V6: Yield distribution */
  YIELD: "apply_segmented_yield_distribution",
  /** V6: Voiding transactions */
  VOID: "void_transaction",
  /** V6: Voiding yield distributions */
  VOID_YIELD: "void_yield_distribution",
} as const;
