/**
 * RPC Function Signatures
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Provides compile-time and runtime verification of RPC calls.
 * Regenerate with: npm run contracts:generate
 */

import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

// =============================================================================
// RPC FUNCTION REGISTRY
// =============================================================================

type RPCFunctions = Database["public"]["Functions"];
export type RPCFunctionName = keyof RPCFunctions;

/** All registered RPC function names */
export const RPC_FUNCTIONS = [
  "_resolve_investor_fee_pct",
  "acquire_delivery_batch",
  "acquire_position_lock",
  "acquire_withdrawal_lock",
  "acquire_yield_lock",
  "add_fund_to_investor",
  "adjust_investor_position",
  "admin_create_transaction",
  "admin_create_transactions_batch",
  "apply_adb_yield_distribution_v3",
  "apply_daily_yield_to_fund_v2",
  "apply_daily_yield_to_fund_v3",
  "apply_daily_yield_with_validation",
  "apply_deposit_with_crystallization",
  "apply_transaction_with_crystallization",
  "apply_withdrawal_with_crystallization",
  "apply_yield_correction_v2",
  "approve_mfa_reset",
  "approve_request",
  "approve_staging_promotion",
  "approve_withdrawal",
  "assert_integrity_or_raise",
  "backfill_balance_chain_fix",
  "batch_crystallize_fund",
  "batch_initialize_fund_aum",
  "batch_reconcile_all_positions",
  "build_error_response",
  "build_success_response",
  "calc_avg_daily_balance",
  "calc_avg_daily_balance_optimized",
  "calculate_position_at_date_fix",
  "calculate_reconciliation_tolerance",
  "can_access_investor",
  "can_access_notification",
  "can_execute_mfa_reset",
  "can_insert_notification",
  "can_withdraw",
  "cancel_delivery",
  "cancel_withdrawal_by_admin",
  "cancel_withdrawal_by_investor",
  "check_all_funds_transaction_aum",
  "check_and_fix_aum_integrity",
  "check_approval_integrity",
  "check_aum_exists_for_date",
  "check_aum_position_health",
  "check_aum_reconciliation",
  "check_duplicate_transaction_refs",
  "check_is_admin",
  "check_platform_data_integrity",
  "check_rate_limit",
  "check_rate_limit_with_config",
  "check_transaction_sources",
  "cleanup_dormant_positions",
  "cleanup_duplicate_preflow_aum",
  "cleanup_expired_approvals",
  "cleanup_test_profiles",
  "complete_withdrawal",
  "compute_correction_input_hash",
  "compute_jsonb_delta",
  "compute_position_from_ledger",
  "create_admin_invite",
  "create_daily_position_snapshot",
  "create_integrity_alert",
  "create_withdrawal_request",
  "crystallize_month_end",
  "crystallize_yield_before_flow",
  "current_user_is_admin_or_owner",
  "delete_transaction",
  "delete_withdrawal",
  "dispatch_report_delivery_run",
  "edit_transaction",
  "ensure_admin",
  "ensure_preflow_aum",
  "export_investor_data",
  "finalize_month_yield",
  "finalize_reconciliation_pack",
  "finalize_statement_period",
  "force_delete_investor",
  "fund_period_return",
  "generate_document_path",
  "generate_reconciliation_pack",
  "generate_staging_preview_report",
  "generate_statement_path",
  "get_admin_name",
  "get_all_dust_tolerances",
  "get_approval_threshold",
  "get_aum_position_reconciliation",
  "get_available_balance",
  "get_delivery_stats",
  "get_dust_tolerance_for_fund",
  "get_existing_preflow_aum",
  "get_fund_aum_as_of",
  "get_fund_base_asset",
  "get_fund_composition",
  "get_fund_nav_history",
  "get_fund_net_flows",
  "get_fund_summary",
  "get_funds_with_aum",
  "get_health_trend",
  "get_historical_nav",
  "get_ib_parent_candidates",
  "get_ib_referral_count",
  "get_ib_referral_detail",
  "get_ib_referrals",
  "get_investor_fee_pct",
  "get_investor_ib_pct",
  "get_investor_remaining_loss",
  "get_kpi_metrics",
  "get_latest_health_status",
  "get_monthly_platform_aum",
  "get_pending_approval",
  "get_position_reconciliation",
  "get_report_statistics",
  "get_reporting_eligible_investors",
  "get_schema_dump",
  "get_statement_period_summary",
  "get_statement_signed_url",
  "get_system_mode",
  "get_transaction_aum",
  "get_user_admin_status",
  "get_user_reports",
  "get_void_aum_impact",
  "get_void_transaction_impact",
  "get_void_yield_impact",
  "get_yield_corrections",
  "has_finalized_recon_pack",
  "has_role",
  "has_super_admin_role",
  "has_valid_approval",
  "initialize_all_hwm_values",
  "initialize_crystallization_dates",
  "initialize_fund_aum_from_positions",
  "initialize_null_crystallization_dates",
  "insert_yield_transaction",
  "internal_route_to_fees",
  "is_admin",
  "is_admin_for_jwt",
  "is_admin_safe",
  "is_canonical_rpc",
  "is_crystallization_current",
  "is_import_enabled",
  "is_period_locked",
  "is_super_admin",
  "is_valid_share_token",
  "is_within_edit_window",
  "is_yield_period_closed",
  "list_pending_staging_approvals",
  "lock_accounting_period",
  "lock_imports",
  "lock_period_with_approval",
  "log_audit_event",
  "log_financial_operation",
  "log_ledger_mismatches",
  "log_security_event",
  "log_withdrawal_action",
  "mark_delivery_result",
  "mark_mfa_reset_executed",
  "mark_sent_manually",
  "merge_duplicate_profiles",
  "nightly_aum_reconciliation",
  "offset_losses_with_gain",
  "parse_platform_error",
  "populate_daily_balances",
  "populate_investor_fund_performance",
  "preview_adb_yield_distribution_v3",
  "preview_crystallization",
  "preview_daily_yield_to_fund_v3",
  "preview_merge_duplicate_profiles",
  "preview_yield_correction_v2",
  "process_excel_import_with_classes",
  "process_yield_distribution",
  "process_yield_distribution_with_dust",
  "promote_staging_batch",
  "queue_statement_deliveries",
  "raise_platform_error",
  "rebuild_investor_period_balances",
  "rebuild_position_from_ledger",
  "recalc_daily_balance",
  "recalculate_all_aum",
  "recalculate_fund_aum_for_date",
  "recompute_investor_position",
  "recompute_investor_positions_for_investor",
  "reconcile_all_positions",
  "reconcile_fund_aum_with_positions",
  "reconcile_fund_period",
  "reconcile_investor_position",
  "reconcile_investor_position_internal",
  "record_investor_loss",
  "refresh_materialized_view_concurrently",
  "refresh_yield_materialized_views",
  "regenerate_reports_for_correction",
  "reject_mfa_reset",
  "reject_request",
  "reject_staging_promotion",
  "reject_withdrawal",
  "reopen_yield_period",
  "repair_all_positions",
  "replace_aum_snapshot",
  "request_approval",
  "request_mfa_reset",
  "request_staging_promotion_approval",
  "requeue_stale_sending",
  "require_admin",
  "require_super_admin",
  "requires_dual_approval",
  "reset_all_data_keep_profiles",
  "reset_all_investor_positions",
  "retry_delivery",
  "rollback_yield_correction",
  "route_withdrawal_to_fees",
  "run_comprehensive_health_check",
  "run_daily_health_check",
  "run_integrity_check",
  "run_integrity_pack",
  "send_daily_rate_notifications",
  "set_canonical_rpc",
  "set_fund_daily_aum",
  "start_processing_withdrawal",
  "sync_all_fund_aum",
  "sync_aum_to_positions",
  "system_health_check",
  "test_apply_daily_yield_v3",
  "test_apply_yield_distribution",
  "test_profiles_access",
  "unlock_imports",
  "update_admin_role",
  "update_dust_tolerance",
  "update_fund_aum_baseline",
  "update_fund_daily_aum",
  "update_fund_daily_aum_with_recalc",
  "update_investor_aum_percentages",
  "update_transaction",
  "update_user_profile_secure",
  "update_withdrawal",
  "upsert_fund_aum_after_yield",
  "use_invite_code",
  "validate_aum_against_positions",
  "validate_aum_against_positions_at_date",
  "validate_aum_matches_positions",
  "validate_aum_matches_positions_strict",
  "validate_invite_code",
  "validate_pre_yield_aum",
  "validate_staging_batch",
  "validate_staging_row",
  "validate_transaction_aum_exists",
  "validate_withdrawal_transition",
  "validate_yield_distribution_prerequisites",
  "validate_yield_parameters",
  "validate_yield_rate_sanity",
  "validate_yield_temporal_lock",
  "verify_aum_purpose_usage",
  "verify_yield_calculation_integrity",
  "verify_yield_distribution_balance",
  "void_and_reissue_transaction",
  "void_fund_daily_aum",
  "void_investor_yield_events_for_distribution",
  "void_transaction",
  "void_transaction_with_approval",
  "void_yield_distribution",
] as const;

// =============================================================================
// RPC SIGNATURES METADATA
// =============================================================================

export const RPC_SIGNATURES = {
  _resolve_investor_fee_pct: {
    name: "_resolve_investor_fee_pct" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  acquire_delivery_batch: {
    name: "acquire_delivery_batch" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_batch_size", "p_channel", "p_worker_id"] as const,
  },
  acquire_position_lock: {
    name: "acquire_position_lock" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  acquire_withdrawal_lock: {
    name: "acquire_withdrawal_lock" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [] as const,
  },
  acquire_yield_lock: {
    name: "acquire_yield_lock" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  add_fund_to_investor: {
    name: "add_fund_to_investor" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_cost_basis", "p_initial_shares"] as const,
  },
  adjust_investor_position: {
    name: "adjust_investor_position" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_investor_id", "p_fund_id", "p_amount", "p_reason"] as const,
    optionalParams: ["p_tx_date", "p_admin_id"] as const,
  },
  admin_create_transaction: {
    name: "admin_create_transaction" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id", "p_tx_date", "p_type"] as const,
    optionalParams: ["p_admin_id", "p_notes", "p_reference_id"] as const,
  },
  admin_create_transactions_batch: {
    name: "admin_create_transactions_batch" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_requests"] as const,
    optionalParams: [] as const,
  },
  apply_adb_yield_distribution_v3: {
    name: "apply_adb_yield_distribution_v3" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [
      "p_fund_id",
      "p_gross_yield_amount",
      "p_period_end",
      "p_period_start",
    ] as const,
    optionalParams: ["p_admin_id", "p_distribution_date", "p_purpose"] as const,
  },
  apply_daily_yield_to_fund_v2: {
    name: "apply_daily_yield_to_fund_v2" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id", "p_date", "p_gross_yield"] as const,
    optionalParams: ["p_purpose", "p_notes"] as const,
  },
  apply_daily_yield_to_fund_v3: {
    name: "apply_daily_yield_to_fund_v3" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: ["p_created_by", "p_purpose"] as const,
  },
  apply_daily_yield_with_validation: {
    name: "apply_daily_yield_with_validation" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_created_by", "p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: ["p_purpose", "p_skip_validation"] as const,
  },
  apply_deposit_with_crystallization: {
    name: "apply_deposit_with_crystallization" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_closing_aum",
      "p_effective_date",
      "p_fund_id",
      "p_investor_id",
    ] as const,
    optionalParams: ["p_notes", "p_purpose", "p_tx_hash", "p_tx_subtype"] as const,
  },
  apply_transaction_with_crystallization: {
    name: "apply_transaction_with_crystallization" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [
      "p_amount",
      "p_fund_id",
      "p_investor_id",
      "p_reference_id",
      "p_tx_date",
      "p_tx_type",
    ] as const,
    optionalParams: [
      "p_admin_id",
      "p_distribution_id",
      "p_new_total_aum",
      "p_notes",
      "p_purpose",
    ] as const,
  },
  apply_withdrawal_with_crystallization: {
    name: "apply_withdrawal_with_crystallization" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_fund_id",
      "p_investor_id",
      "p_new_total_aum",
      "p_tx_date",
    ] as const,
    optionalParams: ["p_notes", "p_purpose", "p_tx_hash", "p_tx_subtype"] as const,
  },
  apply_yield_correction_v2: {
    name: "apply_yield_correction_v2" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_confirmation",
      "p_fund_id",
      "p_new_aum",
      "p_period_end",
      "p_period_start",
      "p_purpose",
      "p_reason",
    ] as const,
    optionalParams: [] as const,
  },
  approve_mfa_reset: {
    name: "approve_mfa_reset" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  approve_request: {
    name: "approve_request" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_approval_id", "p_approver_id"] as const,
    optionalParams: ["p_notes"] as const,
  },
  approve_staging_promotion: {
    name: "approve_staging_promotion" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_approval_id", "p_approved_by"] as const,
    optionalParams: ["p_closing_aum"] as const,
  },
  approve_withdrawal: {
    name: "approve_withdrawal" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: ["p_admin_notes", "p_approved_amount"] as const,
  },
  assert_integrity_or_raise: {
    name: "assert_integrity_or_raise" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_context", "p_scope_fund_id", "p_scope_investor_id"] as const,
  },
  backfill_balance_chain_fix: {
    name: "backfill_balance_chain_fix" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  batch_crystallize_fund: {
    name: "batch_crystallize_fund" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id", "p_effective_date", "p_force_override"] as const,
    optionalParams: [] as const,
  },
  batch_initialize_fund_aum: {
    name: "batch_initialize_fund_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_admin_id", "p_dry_run"] as const,
  },
  batch_reconcile_all_positions: {
    name: "batch_reconcile_all_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  build_error_response: {
    name: "build_error_response" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_code"] as const,
    optionalParams: ["p_details"] as const,
  },
  build_success_response: {
    name: "build_success_response" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_data", "p_message"] as const,
  },
  calc_avg_daily_balance: {
    name: "calc_avg_daily_balance" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id", "p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  calc_avg_daily_balance_optimized: {
    name: "calc_avg_daily_balance_optimized" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id", "p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  calculate_position_at_date_fix: {
    name: "calculate_position_at_date_fix" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  calculate_reconciliation_tolerance: {
    name: "calculate_reconciliation_tolerance" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum"] as const,
    optionalParams: ["p_tier"] as const,
  },
  can_access_investor: {
    name: "can_access_investor" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["investor_uuid"] as const,
    optionalParams: [] as const,
  },
  can_access_notification: {
    name: "can_access_notification" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["notification_id"] as const,
    optionalParams: [] as const,
  },
  can_execute_mfa_reset: {
    name: "can_execute_mfa_reset" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_user_id"] as const,
  },
  can_insert_notification: {
    name: "can_insert_notification" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  can_withdraw: {
    name: "can_withdraw" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  cancel_delivery: {
    name: "cancel_delivery" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: [] as const,
  },
  cancel_withdrawal_by_admin: {
    name: "cancel_withdrawal_by_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_request_id"] as const,
    optionalParams: ["p_admin_notes"] as const,
  },
  cancel_withdrawal_by_investor: {
    name: "cancel_withdrawal_by_investor" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id", "p_request_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
  check_all_funds_transaction_aum: {
    name: "check_all_funds_transaction_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_tx_date"] as const,
    optionalParams: [] as const,
  },
  check_and_fix_aum_integrity: {
    name: "check_and_fix_aum_integrity" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_dry_run", "p_end_date", "p_fund_id", "p_start_date"] as const,
  },
  check_approval_integrity: {
    name: "check_approval_integrity" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_aum_exists_for_date: {
    name: "check_aum_exists_for_date" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: [] as const,
  },
  check_aum_position_health: {
    name: "check_aum_position_health" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_aum_reconciliation: {
    name: "check_aum_reconciliation" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_tolerance_pct"] as const,
  },
  check_duplicate_transaction_refs: {
    name: "check_duplicate_transaction_refs" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_is_admin: {
    name: "check_is_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["user_id"] as const,
    optionalParams: [] as const,
  },
  check_platform_data_integrity: {
    name: "check_platform_data_integrity" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  check_rate_limit: {
    name: "check_rate_limit" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action_type", "p_actor_id"] as const,
    optionalParams: ["p_max_actions", "p_window_minutes"] as const,
  },
  check_rate_limit_with_config: {
    name: "check_rate_limit_with_config" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action_type", "p_actor_id"] as const,
    optionalParams: [] as const,
  },
  check_transaction_sources: {
    name: "check_transaction_sources" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  cleanup_dormant_positions: {
    name: "cleanup_dormant_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  cleanup_duplicate_preflow_aum: {
    name: "cleanup_duplicate_preflow_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  cleanup_expired_approvals: {
    name: "cleanup_expired_approvals" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  cleanup_test_profiles: {
    name: "cleanup_test_profiles" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  complete_withdrawal: {
    name: "complete_withdrawal" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_closing_aum", "p_request_id"] as const,
    optionalParams: ["p_admin_notes", "p_event_ts", "p_transaction_hash"] as const,
  },
  compute_correction_input_hash: {
    name: "compute_correction_input_hash" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_fund_id",
      "p_new_aum",
      "p_period_end",
      "p_period_start",
      "p_purpose",
    ] as const,
    optionalParams: [] as const,
  },
  compute_jsonb_delta: {
    name: "compute_jsonb_delta" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_new", "p_old"] as const,
    optionalParams: [] as const,
  },
  compute_position_from_ledger: {
    name: "compute_position_from_ledger" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_as_of"] as const,
  },
  create_admin_invite: {
    name: "create_admin_invite" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_email"] as const,
    optionalParams: [] as const,
  },
  create_daily_position_snapshot: {
    name: "create_daily_position_snapshot" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_fund_id", "p_snapshot_date"] as const,
  },
  create_integrity_alert: {
    name: "create_integrity_alert" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_alert_type", "p_message", "p_severity", "p_title"] as const,
    optionalParams: ["p_metadata"] as const,
  },
  create_withdrawal_request: {
    name: "create_withdrawal_request" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_amount", "p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_notes", "p_type"] as const,
  },
  crystallize_month_end: {
    name: "crystallize_month_end" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_closing_aum", "p_fund_id", "p_month_end_date"] as const,
    optionalParams: [] as const,
  },
  crystallize_yield_before_flow: {
    name: "crystallize_yield_before_flow" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [
      "p_admin_id",
      "p_closing_aum",
      "p_event_ts",
      "p_fund_id",
      "p_trigger_reference",
      "p_trigger_type",
    ] as const,
    optionalParams: ["p_purpose"] as const,
  },
  current_user_is_admin_or_owner: {
    name: "current_user_is_admin_or_owner" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["check_user_id"] as const,
    optionalParams: [] as const,
  },
  delete_transaction: {
    name: "delete_transaction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_confirmation", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  delete_withdrawal: {
    name: "delete_withdrawal" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_withdrawal_id"] as const,
    optionalParams: ["p_hard_delete"] as const,
  },
  dispatch_report_delivery_run: {
    name: "dispatch_report_delivery_run" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_channel"] as const,
  },
  edit_transaction: {
    name: "edit_transaction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_transaction_id"] as const,
    optionalParams: ["p_notes", "p_reference_id", "p_tx_date", "p_tx_hash"] as const,
  },
  ensure_admin: {
    name: "ensure_admin" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  ensure_preflow_aum: {
    name: "ensure_preflow_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_date", "p_fund_id", "p_purpose", "p_total_aum"] as const,
    optionalParams: [] as const,
  },
  export_investor_data: {
    name: "export_investor_data" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  finalize_month_yield: {
    name: "finalize_month_yield" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_period_month", "p_period_year"] as const,
    optionalParams: [] as const,
  },
  finalize_reconciliation_pack: {
    name: "finalize_reconciliation_pack" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_pack_id"] as const,
    optionalParams: [] as const,
  },
  finalize_statement_period: {
    name: "finalize_statement_period" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_period_id"] as const,
    optionalParams: [] as const,
  },
  force_delete_investor: {
    name: "force_delete_investor" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_investor_id", "p_admin_id"] as const,
    optionalParams: [] as const,
  },
  fund_period_return: {
    name: "fund_period_return" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["d1", "d2", "f"] as const,
    optionalParams: ["net"] as const,
  },
  generate_document_path: {
    name: "generate_document_path" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["document_type", "filename", "user_id"] as const,
    optionalParams: [] as const,
  },
  generate_reconciliation_pack: {
    name: "generate_reconciliation_pack" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  generate_staging_preview_report: {
    name: "generate_staging_preview_report" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_batch_id"] as const,
    optionalParams: [] as const,
  },
  generate_statement_path: {
    name: "generate_statement_path" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["month", "user_id", "year"] as const,
    optionalParams: ["fund_code"] as const,
  },
  get_admin_name: {
    name: "get_admin_name" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["admin_id"] as const,
    optionalParams: [] as const,
  },
  get_all_dust_tolerances: {
    name: "get_all_dust_tolerances" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_approval_threshold: {
    name: "get_approval_threshold" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_operation"] as const,
    optionalParams: [] as const,
  },
  get_aum_position_reconciliation: {
    name: "get_aum_position_reconciliation" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_date"] as const,
  },
  get_available_balance: {
    name: "get_available_balance" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_delivery_stats: {
    name: "get_delivery_stats" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_dust_tolerance_for_fund: {
    name: "get_dust_tolerance_for_fund" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_existing_preflow_aum: {
    name: "get_existing_preflow_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_event_date", "p_fund_id", "p_purpose"] as const,
    optionalParams: [] as const,
  },
  get_fund_aum_as_of: {
    name: "get_fund_aum_as_of" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_as_of_date", "p_fund_id"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  get_fund_base_asset: {
    name: "get_fund_base_asset" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_fund_composition: {
    name: "get_fund_composition" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: [] as const,
  },
  get_fund_nav_history: {
    name: "get_fund_nav_history" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_end_date", "p_fund_id", "p_start_date"] as const,
    optionalParams: [] as const,
  },
  get_fund_net_flows: {
    name: "get_fund_net_flows" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_end_date", "p_fund_id", "p_start_date"] as const,
    optionalParams: [] as const,
  },
  get_fund_summary: {
    name: "get_fund_summary" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_funds_with_aum: {
    name: "get_funds_with_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_health_trend: {
    name: "get_health_trend" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_days"] as const,
  },
  get_historical_nav: {
    name: "get_historical_nav" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["target_date"] as const,
    optionalParams: [] as const,
  },
  get_ib_parent_candidates: {
    name: "get_ib_parent_candidates" as const,
    returnType: "Record",
    returnsSet: true,
    securityDefiner: true,
    requiredParams: ["p_exclude_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referral_count: {
    name: "get_ib_referral_count" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_ib_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referral_detail: {
    name: "get_ib_referral_detail" as const,
    returnType: "Record",
    returnsSet: true,
    securityDefiner: true,
    requiredParams: ["p_ib_id", "p_referral_id"] as const,
    optionalParams: [] as const,
  },
  get_ib_referrals: {
    name: "get_ib_referrals" as const,
    returnType: "Record",
    returnsSet: true,
    securityDefiner: true,
    requiredParams: ["p_ib_id"] as const,
    optionalParams: ["p_limit", "p_offset"] as const,
  },
  get_investor_fee_pct: {
    name: "get_investor_fee_pct" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_effective_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_investor_ib_pct: {
    name: "get_investor_ib_pct" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_investor_remaining_loss: {
    name: "get_investor_remaining_loss" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  get_kpi_metrics: {
    name: "get_kpi_metrics" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [] as const,
    optionalParams: ["metric_type", "user_id", "p_date_range"] as const,
  },
  get_latest_health_status: {
    name: "get_latest_health_status" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_monthly_platform_aum: {
    name: "get_monthly_platform_aum" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_pending_approval: {
    name: "get_pending_approval" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action_type", "p_entity_id", "p_entity_type"] as const,
    optionalParams: [] as const,
  },
  get_position_reconciliation: {
    name: "get_position_reconciliation" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_as_of_date", "p_fund_id"] as const,
  },
  get_report_statistics: {
    name: "get_report_statistics" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  get_reporting_eligible_investors: {
    name: "get_reporting_eligible_investors" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_schema_dump: {
    name: "get_schema_dump" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_statement_period_summary: {
    name: "get_statement_period_summary" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: [] as const,
  },
  get_statement_signed_url: {
    name: "get_statement_signed_url" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_storage_path"] as const,
    optionalParams: ["p_expires_in"] as const,
  },
  get_system_mode: {
    name: "get_system_mode" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  get_transaction_aum: {
    name: "get_transaction_aum" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_tx_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  get_user_admin_status: {
    name: "get_user_admin_status" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["user_id"] as const,
    optionalParams: [] as const,
  },
  get_user_reports: {
    name: "get_user_reports" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: ["p_limit"] as const,
  },
  get_void_aum_impact: {
    name: "get_void_aum_impact" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_record_id"] as const,
    optionalParams: [] as const,
  },
  get_void_transaction_impact: {
    name: "get_void_transaction_impact" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  get_void_yield_impact: {
    name: "get_void_yield_impact" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_distribution_id"] as const,
    optionalParams: [] as const,
  },
  get_yield_corrections: {
    name: "get_yield_corrections" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_date_from", "p_date_to", "p_fund_id"] as const,
  },
  has_finalized_recon_pack: {
    name: "has_finalized_recon_pack" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_period_end", "p_period_start"] as const,
    optionalParams: [] as const,
  },
  has_role: {
    name: "has_role" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["_role", "_user_id"] as const,
    optionalParams: [] as const,
  },
  has_super_admin_role: {
    name: "has_super_admin_role" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  has_valid_approval: {
    name: "has_valid_approval" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action_type", "p_entity_id", "p_entity_type"] as const,
    optionalParams: [] as const,
  },
  initialize_all_hwm_values: {
    name: "initialize_all_hwm_values" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  initialize_crystallization_dates: {
    name: "initialize_crystallization_dates" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_admin_id", "p_dry_run", "p_fund_id"] as const,
  },
  initialize_fund_aum_from_positions: {
    name: "initialize_fund_aum_from_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_admin_id", "p_aum_date"] as const,
  },
  initialize_null_crystallization_dates: {
    name: "initialize_null_crystallization_dates" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  insert_yield_transaction: {
    name: "insert_yield_transaction" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_fund_code",
      "p_investor_name",
      "p_month",
      "p_tx_date",
    ] as const,
    optionalParams: [] as const,
  },
  internal_route_to_fees: {
    name: "internal_route_to_fees" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_admin_id",
      "p_amount",
      "p_effective_date",
      "p_from_investor_id",
      "p_fund_id",
      "p_reason",
    ] as const,
    optionalParams: ["p_transfer_id"] as const,
  },
  is_admin: {
    name: "is_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_admin_for_jwt: {
    name: "is_admin_for_jwt" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_admin_safe: {
    name: "is_admin_safe" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_canonical_rpc: {
    name: "is_canonical_rpc" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_crystallization_current: {
    name: "is_crystallization_current" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_target_date"] as const,
  },
  is_import_enabled: {
    name: "is_import_enabled" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  is_period_locked: {
    name: "is_period_locked" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: [] as const,
  },
  is_super_admin: {
    name: "is_super_admin" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: [] as const,
  },
  is_valid_share_token: {
    name: "is_valid_share_token" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["token_value"] as const,
    optionalParams: [] as const,
  },
  is_within_edit_window: {
    name: "is_within_edit_window" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_created_at"] as const,
    optionalParams: [] as const,
  },
  is_yield_period_closed: {
    name: "is_yield_period_closed" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_month", "p_purpose", "p_year"] as const,
    optionalParams: [] as const,
  },
  list_pending_staging_approvals: {
    name: "list_pending_staging_approvals" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  lock_accounting_period: {
    name: "lock_accounting_period" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_period_end", "p_period_start"] as const,
    optionalParams: ["p_notes"] as const,
  },
  lock_imports: {
    name: "lock_imports" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_reason"] as const,
  },
  lock_period_with_approval: {
    name: "lock_period_with_approval" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_period_end", "p_period_start"] as const,
    optionalParams: ["p_notes"] as const,
  },
  log_audit_event: {
    name: "log_audit_event" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_entity"] as const,
    optionalParams: ["p_entity_id", "p_meta", "p_new_values", "p_old_values"] as const,
  },
  log_financial_operation: {
    name: "log_financial_operation" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_entity", "p_entity_id"] as const,
    optionalParams: ["p_meta", "p_new_values", "p_old_values"] as const,
  },
  log_ledger_mismatches: {
    name: "log_ledger_mismatches" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  log_security_event: {
    name: "log_security_event" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_event_type", "p_severity"] as const,
    optionalParams: ["p_details", "p_user_id"] as const,
  },
  log_withdrawal_action: {
    name: "log_withdrawal_action" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_action", "p_request_id"] as const,
    optionalParams: ["p_details"] as const,
  },
  mark_delivery_result: {
    name: "mark_delivery_result" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id", "p_success"] as const,
    optionalParams: ["p_error_code", "p_error_message", "p_provider_message_id"] as const,
  },
  mark_mfa_reset_executed: {
    name: "mark_mfa_reset_executed" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [] as const,
  },
  mark_sent_manually: {
    name: "mark_sent_manually" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: ["p_note"] as const,
  },
  merge_duplicate_profiles: {
    name: "merge_duplicate_profiles" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_keep_profile_id", "p_merge_profile_id"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  nightly_aum_reconciliation: {
    name: "nightly_aum_reconciliation" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  offset_losses_with_gain: {
    name: "offset_losses_with_gain" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_gain", "p_investor_id"] as const,
    optionalParams: ["p_distribution_id"] as const,
  },
  parse_platform_error: {
    name: "parse_platform_error" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_message"] as const,
    optionalParams: [] as const,
  },
  populate_daily_balances: {
    name: "populate_daily_balances" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_end_date", "p_fund_id", "p_start_date"] as const,
    optionalParams: [] as const,
  },
  populate_investor_fund_performance: {
    name: "populate_investor_fund_performance" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_investor_id"] as const,
  },
  preview_adb_yield_distribution_v3: {
    name: "preview_adb_yield_distribution_v3" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: [
      "p_fund_id",
      "p_gross_yield_amount",
      "p_period_end",
      "p_period_start",
    ] as const,
    optionalParams: ["p_purpose"] as const,
  },
  preview_crystallization: {
    name: "preview_crystallization" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_new_total_aum", "p_target_date"] as const,
  },
  preview_daily_yield_to_fund_v3: {
    name: "preview_daily_yield_to_fund_v3" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_new_aum", "p_yield_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  preview_merge_duplicate_profiles: {
    name: "preview_merge_duplicate_profiles" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_keep_profile_id", "p_merge_profile_id"] as const,
    optionalParams: [] as const,
  },
  preview_yield_correction_v2: {
    name: "preview_yield_correction_v2" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_fund_id",
      "p_new_aum",
      "p_period_end",
      "p_period_start",
      "p_purpose",
    ] as const,
    optionalParams: [] as const,
  },
  process_excel_import_with_classes: {
    name: "process_excel_import_with_classes" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_data"] as const,
    optionalParams: ["p_import_type"] as const,
  },
  process_yield_distribution: {
    name: "process_yield_distribution" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id", "p_gross_amount"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  process_yield_distribution_with_dust: {
    name: "process_yield_distribution_with_dust" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id", "p_gross_amount"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  promote_staging_batch: {
    name: "promote_staging_batch" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_batch_id", "p_closing_aum"] as const,
    optionalParams: [] as const,
  },
  queue_statement_deliveries: {
    name: "queue_statement_deliveries" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_channel", "p_fund_id", "p_investor_ids"] as const,
  },
  raise_platform_error: {
    name: "raise_platform_error" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_error_code"] as const,
    optionalParams: ["p_details"] as const,
  },
  rebuild_investor_period_balances: {
    name: "rebuild_investor_period_balances" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_period_end", "p_period_start", "p_purpose"] as const,
    optionalParams: [] as const,
  },
  rebuild_position_from_ledger: {
    name: "rebuild_position_from_ledger" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_investor_id", "p_reason"] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  recalc_daily_balance: {
    name: "recalc_daily_balance" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_balance_date", "p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  recalculate_all_aum: {
    name: "recalculate_all_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  recalculate_fund_aum_for_date: {
    name: "recalculate_fund_aum_for_date" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: ["p_actor_id", "p_purpose"] as const,
  },
  recompute_investor_position: {
    name: "recompute_investor_position" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  recompute_investor_positions_for_investor: {
    name: "recompute_investor_positions_for_investor" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_investor_id"] as const,
    optionalParams: [] as const,
  },
  reconcile_all_positions: {
    name: "reconcile_all_positions" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_dry_run"] as const,
  },
  reconcile_fund_aum_with_positions: {
    name: "reconcile_fund_aum_with_positions" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  reconcile_fund_period: {
    name: "reconcile_fund_period" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_end_date", "p_fund_id", "p_start_date"] as const,
    optionalParams: [] as const,
  },
  reconcile_investor_position: {
    name: "reconcile_investor_position" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_fund_id", "p_investor_id"] as const,
    optionalParams: ["p_action"] as const,
  },
  reconcile_investor_position_internal: {
    name: "reconcile_investor_position_internal" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id"] as const,
    optionalParams: [] as const,
  },
  record_investor_loss: {
    name: "record_investor_loss" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_investor_id", "p_loss_amount", "p_period_end"] as const,
    optionalParams: ["p_distribution_id"] as const,
  },
  refresh_materialized_view_concurrently: {
    name: "refresh_materialized_view_concurrently" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["view_name"] as const,
    optionalParams: [] as const,
  },
  refresh_yield_materialized_views: {
    name: "refresh_yield_materialized_views" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  regenerate_reports_for_correction: {
    name: "regenerate_reports_for_correction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_correction_id"] as const,
    optionalParams: [] as const,
  },
  reject_mfa_reset: {
    name: "reject_mfa_reset" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_request_id"] as const,
    optionalParams: ["p_admin_id"] as const,
  },
  reject_request: {
    name: "reject_request" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_approval_id", "p_rejection_reason", "p_rejector_id"] as const,
    optionalParams: [] as const,
  },
  reject_staging_promotion: {
    name: "reject_staging_promotion" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_approval_id", "p_reason", "p_rejected_by"] as const,
    optionalParams: [] as const,
  },
  reject_withdrawal: {
    name: "reject_withdrawal" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_request_id"] as const,
    optionalParams: ["p_admin_notes"] as const,
  },
  reopen_yield_period: {
    name: "reopen_yield_period" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_month", "p_purpose", "p_reason", "p_year"] as const,
    optionalParams: [] as const,
  },
  repair_all_positions: {
    name: "repair_all_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  replace_aum_snapshot: {
    name: "replace_aum_snapshot" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum_date", "p_fund_id", "p_new_total_aum"] as const,
    optionalParams: ["p_admin_id", "p_purpose", "p_reason"] as const,
  },
  request_approval: {
    name: "request_approval" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [
      "p_action_type",
      "p_entity_id",
      "p_entity_type",
      "p_reason",
      "p_requester_id",
    ] as const,
    optionalParams: ["p_amount", "p_expiry_hours", "p_metadata"] as const,
  },
  request_mfa_reset: {
    name: "request_mfa_reset" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason"] as const,
    optionalParams: ["p_ip", "p_user_agent"] as const,
  },
  request_staging_promotion_approval: {
    name: "request_staging_promotion_approval" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_batch_id", "p_requested_by"] as const,
    optionalParams: ["p_reason"] as const,
  },
  requeue_stale_sending: {
    name: "requeue_stale_sending" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_period_id"] as const,
    optionalParams: ["p_minutes"] as const,
  },
  require_admin: {
    name: "require_admin" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_operation"] as const,
  },
  require_super_admin: {
    name: "require_super_admin" as const,
    returnType: "string",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_operation", "p_actor_id"] as const,
    optionalParams: [] as const,
  },
  requires_dual_approval: {
    name: "requires_dual_approval" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_operation"] as const,
    optionalParams: ["p_amount"] as const,
  },
  reset_all_data_keep_profiles: {
    name: "reset_all_data_keep_profiles" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_confirmation_code"] as const,
    optionalParams: [] as const,
  },
  reset_all_investor_positions: {
    name: "reset_all_investor_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_confirmation_code"] as const,
    optionalParams: [] as const,
  },
  retry_delivery: {
    name: "retry_delivery" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_delivery_id"] as const,
    optionalParams: [] as const,
  },
  rollback_yield_correction: {
    name: "rollback_yield_correction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_correction_id", "p_reason"] as const,
    optionalParams: [] as const,
  },
  route_withdrawal_to_fees: {
    name: "route_withdrawal_to_fees" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_request_id", "p_actor_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
  run_comprehensive_health_check: {
    name: "run_comprehensive_health_check" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  run_daily_health_check: {
    name: "run_daily_health_check" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  run_integrity_check: {
    name: "run_integrity_check" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_scope_fund_id", "p_scope_investor_id"] as const,
  },
  run_integrity_pack: {
    name: "run_integrity_pack" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  send_daily_rate_notifications: {
    name: "send_daily_rate_notifications" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_rate_date"] as const,
    optionalParams: [] as const,
  },
  set_canonical_rpc: {
    name: "set_canonical_rpc" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["enabled"] as const,
  },
  set_fund_daily_aum: {
    name: "set_fund_daily_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum_date", "p_fund_id", "p_total_aum"] as const,
    optionalParams: ["p_purpose", "p_skip_validation", "p_source"] as const,
  },
  start_processing_withdrawal: {
    name: "start_processing_withdrawal" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_request_id"] as const,
    optionalParams: [
      "p_admin_notes",
      "p_processed_amount",
      "p_settlement_date",
      "p_tx_hash",
    ] as const,
  },
  sync_all_fund_aum: {
    name: "sync_all_fund_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: ["p_target_date"] as const,
  },
  sync_aum_to_positions: {
    name: "sync_aum_to_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_admin_id", "p_aum_date", "p_purpose", "p_reason"] as const,
  },
  system_health_check: {
    name: "system_health_check" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  test_apply_daily_yield_v3: {
    name: "test_apply_daily_yield_v3" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_actor_id", "p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  test_apply_yield_distribution: {
    name: "test_apply_yield_distribution" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_actor_id", "p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  test_profiles_access: {
    name: "test_profiles_access" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  unlock_imports: {
    name: "unlock_imports" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  update_admin_role: {
    name: "update_admin_role" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_new_role", "p_target_user_id"] as const,
    optionalParams: [] as const,
  },
  update_dust_tolerance: {
    name: "update_dust_tolerance" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_asset", "p_tolerance"] as const,
    optionalParams: [] as const,
  },
  update_fund_aum_baseline: {
    name: "update_fund_aum_baseline" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_new_baseline"] as const,
    optionalParams: [] as const,
  },
  update_fund_daily_aum: {
    name: "update_fund_daily_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_new_total_aum", "p_reason", "p_record_id"] as const,
    optionalParams: [] as const,
  },
  update_fund_daily_aum_with_recalc: {
    name: "update_fund_daily_aum_with_recalc" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_new_total_aum", "p_reason", "p_record_id"] as const,
    optionalParams: [] as const,
  },
  update_investor_aum_percentages: {
    name: "update_investor_aum_percentages" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: [] as const,
  },
  update_transaction: {
    name: "update_transaction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_reason", "p_transaction_id", "p_updates"] as const,
    optionalParams: [] as const,
  },
  update_user_profile_secure: {
    name: "update_user_profile_secure" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_user_id"] as const,
    optionalParams: ["p_first_name", "p_last_name", "p_phone", "p_status"] as const,
  },
  update_withdrawal: {
    name: "update_withdrawal" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_withdrawal_id"] as const,
    optionalParams: ["p_notes", "p_reason", "p_requested_amount", "p_withdrawal_type"] as const,
  },
  upsert_fund_aum_after_yield: {
    name: "upsert_fund_aum_after_yield" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_fund_id", "p_aum_date"] as const,
    optionalParams: [
      "p_total_aum",
      "p_source",
      "p_yield_amount",
      "p_purpose",
      "p_actor_id",
    ] as const,
  },
  use_invite_code: {
    name: "use_invite_code" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_invite_code", "p_user_id"] as const,
    optionalParams: [] as const,
  },
  validate_aum_against_positions: {
    name: "validate_aum_against_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_aum_value", "p_fund_id"] as const,
    optionalParams: ["p_context", "p_max_deviation_pct"] as const,
  },
  validate_aum_against_positions_at_date: {
    name: "validate_aum_against_positions_at_date" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_aum_value", "p_event_date"] as const,
    optionalParams: ["p_max_deviation_pct", "p_context"] as const,
  },
  validate_aum_matches_positions: {
    name: "validate_aum_matches_positions" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_aum_date", "p_purpose", "p_tolerance_pct"] as const,
  },
  validate_aum_matches_positions_strict: {
    name: "validate_aum_matches_positions_strict" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_aum_date", "p_purpose"] as const,
  },
  validate_invite_code: {
    name: "validate_invite_code" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_invite_code"] as const,
    optionalParams: [] as const,
  },
  validate_pre_yield_aum: {
    name: "validate_pre_yield_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id"] as const,
    optionalParams: ["p_tolerance_percentage"] as const,
  },
  validate_staging_batch: {
    name: "validate_staging_batch" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_batch_id"] as const,
    optionalParams: [] as const,
  },
  validate_staging_row: {
    name: "validate_staging_row" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_staging_id"] as const,
    optionalParams: [] as const,
  },
  validate_transaction_aum_exists: {
    name: "validate_transaction_aum_exists" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_tx_date"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  validate_withdrawal_transition: {
    name: "validate_withdrawal_transition" as const,
    returnType: "boolean",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_current_status", "p_new_status"] as const,
    optionalParams: [] as const,
  },
  validate_yield_distribution_prerequisites: {
    name: "validate_yield_distribution_prerequisites" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct", "p_yield_date"] as const,
    optionalParams: ["p_admin_id", "p_aum_tolerance_pct", "p_auto_sync", "p_purpose"] as const,
  },
  validate_yield_parameters: {
    name: "validate_yield_parameters" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct", "p_purpose", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  validate_yield_rate_sanity: {
    name: "validate_yield_rate_sanity" as const,
    returnType: "undefined",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_gross_yield_pct"] as const,
    optionalParams: [] as const,
  },
  validate_yield_temporal_lock: {
    name: "validate_yield_temporal_lock" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_fund_id", "p_purpose", "p_yield_date"] as const,
    optionalParams: [] as const,
  },
  verify_aum_purpose_usage: {
    name: "verify_aum_purpose_usage" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  verify_yield_calculation_integrity: {
    name: "verify_yield_calculation_integrity" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: [] as const,
    optionalParams: [] as const,
  },
  verify_yield_distribution_balance: {
    name: "verify_yield_distribution_balance" as const,
    returnType: "{",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_date", "p_fund_id"] as const,
    optionalParams: ["p_purpose"] as const,
  },
  void_and_reissue_transaction: {
    name: "void_and_reissue_transaction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_original_tx_id", "p_admin_id", "p_new_amount", "p_new_date"] as const,
    optionalParams: ["p_new_notes", "p_new_tx_hash", "p_closing_aum", "p_reason"] as const,
  },
  void_fund_daily_aum: {
    name: "void_fund_daily_aum" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_record_id"] as const,
    optionalParams: [] as const,
  },
  void_investor_yield_events_for_distribution: {
    name: "void_investor_yield_events_for_distribution" as const,
    returnType: "number",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_distribution_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
  void_transaction: {
    name: "void_transaction" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  void_transaction_with_approval: {
    name: "void_transaction_with_approval" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: false,
    requiredParams: ["p_admin_id", "p_reason", "p_transaction_id"] as const,
    optionalParams: [] as const,
  },
  void_yield_distribution: {
    name: "void_yield_distribution" as const,
    returnType: "Json",
    returnsSet: false,
    securityDefiner: true,
    requiredParams: ["p_admin_id", "p_distribution_id"] as const,
    optionalParams: ["p_reason"] as const,
  },
} as const;

// =============================================================================
// TYPE HELPERS
// =============================================================================

/** Get required parameters for an RPC function */
export type RPCRequiredParams<T extends RPCFunctionName> = T extends keyof typeof RPC_SIGNATURES
  ? (typeof RPC_SIGNATURES)[T]["requiredParams"][number]
  : never;

/** Get optional parameters for an RPC function */
export type RPCOptionalParams<T extends RPCFunctionName> = T extends keyof typeof RPC_SIGNATURES
  ? (typeof RPC_SIGNATURES)[T]["optionalParams"][number]
  : never;

/** Validate that an RPC function exists */
export function isValidRPCFunction(name: string): name is RPCFunctionName {
  return (RPC_FUNCTIONS as readonly string[]).includes(name);
}

/** Get signature metadata for an RPC function */
export function getRPCSignature<T extends RPCFunctionName>(name: T) {
  if (!isValidRPCFunction(name)) {
    throw new Error(`Unknown RPC function: ${name}`);
  }
  return RPC_SIGNATURES[name as keyof typeof RPC_SIGNATURES];
}

// =============================================================================
// CANONICAL MUTATION RPCS
// =============================================================================
// These are the ONLY RPCs that should be used for mutations

export const CANONICAL_MUTATION_RPCS = {
  /** Canonical RPC for deposits (with crystallization) */
  DEPOSIT: "apply_deposit_with_crystallization",
  /** Canonical RPC for withdrawals (with crystallization) */
  WITHDRAWAL: "apply_withdrawal_with_crystallization",
  /** Canonical RPC for yield distribution */
  YIELD: "apply_daily_yield_to_fund_v3",
  /** Canonical RPC for voiding transactions */
  VOID: "void_transaction",
  /** Canonical RPC for admin transaction creation */
  ADMIN_TX: "admin_create_transaction",
} as const;
